//! Refloat generated custom-config bytes and field layout.
//!
//! This module keeps generated byte layout private behind typed Refloat views.

use crate::balance::LoopConfig;
#[cfg(any(test, target_arch = "arm"))]
use crate::bms::{RefloatBmsTemperature, RefloatBmsThresholds};
#[cfg(any(test, target_arch = "arm"))]
use vescpkg_rs::CustomConfigVoltageField;
use vescpkg_rs::prelude::{
    AngleCurrentGain, AngleDegrees, AngularVelocity, ElectricalSpeed, IntegralCurrentGain,
    MahonyPitchGain, MahonyRollGain, MotorCurrent, MotorCurrentLimit, PidScale, RateCurrentGain,
    Ratio, Rpm, SampleRate, Speed, VescSeconds, Voltage,
};
#[cfg(any(test, target_arch = "arm"))]
use vescpkg_rs::prelude::{AudioFrequency, AudioVoltage};
use vescpkg_rs::{
    CustomConfigAngleCurrentGainField, CustomConfigAngleField, CustomConfigAngularVelocityField,
    CustomConfigDurationField, CustomConfigEditor, CustomConfigElectricalSpeedField,
    CustomConfigEnumField, CustomConfigFlagField, CustomConfigFrequencyField, CustomConfigImage,
    CustomConfigIntegralCurrentGainField, CustomConfigMahonyPitchGainField,
    CustomConfigMahonyRollGainField, CustomConfigMotorCurrentField, CustomConfigPidScaleField,
    CustomConfigRateCurrentGainField, CustomConfigRatioField, CustomConfigResetField,
    CustomConfigSampleRateField, CustomConfigScaledVoltageField, CustomConfigSecondsField,
    CustomConfigWireByteField,
};

mod flywheel;
mod handtest_safety;

pub(crate) use flywheel::RefloatFlywheelConfig;

// Refloat v1.2.1 generated custom-config XML blob. Upstream generates this from
// `third_party/refloat/src/conf/settings.xml` via `third_party/refloat/src/Makefile:28-31`
// and exposes `data_refloatconfig_` through `get_cfg_xml` at
// `third_party/refloat/src/main.c:2388-2396`.
vescpkg_rs::firmware_section_static!(
    ".text.refloat_config_xml",
    pub(crate) static REFLOAT_CONFIG_XML: [u8; 25_723] = *include_bytes!("conf/refloatconfig.dat")
);

// Refloat v1.2.1 generated serialized default custom config. Upstream
// `get_cfg(..., is_default=true)` allocates `RefloatConfig`, fills defaults,
// serializes it, then frees it at `third_party/refloat/src/main.c:2335-2356`.
// `third_party/refloat/src/Makefile:12-13` declares the generated
// `conf/confparser.*` files, and `third_party/refloat/src/Makefile:28-29`
// regenerates them from `third_party/refloat/src/conf/settings.xml`.
vescpkg_rs::firmware_section_static!(
    ".text.refloat_default_config",
    pub(crate) static REFLOAT_DEFAULT_CONFIG: [u8; 276] = *include_bytes!("conf/default_config.dat")
);
// Upstream generated `conf/confparser.h` derives signature `2427955642`
// (`0x90b7a9ba`) and serialized length `276` from
// `third_party/refloat/src/conf/settings.xml`; the generator is wired in
// `third_party/refloat/src/Makefile:12-29`.
pub(crate) const REFLOAT_CONFIG_SIGNATURE_BYTES: [u8; 4] = [0x90, 0xb7, 0xa9, 0xba];
pub(crate) const REFLOAT_CONFIG_LEN: usize = REFLOAT_DEFAULT_CONFIG.len();

fn generated_field<T>(value: Option<T>) -> T {
    value.expect("generated Refloat field must fit its config image")
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(transparent)]
pub(crate) struct RefloatConfigImage(CustomConfigImage<REFLOAT_CONFIG_LEN>);

impl core::ops::Deref for RefloatConfigImage {
    type Target = CustomConfigImage<REFLOAT_CONFIG_LEN>;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl RefloatConfigImage {
    const ATR_FILTER_FIELD: CustomConfigFrequencyField = vescpkg_rs::generated_custom_config_field!(CustomConfigFrequencyField, len: REFLOAT_CONFIG_LEN, offset: 165, scale: 100.0);
    const DUTY_PUSHBACK_ANGLE_FIELD: CustomConfigAngleField = vescpkg_rs::generated_custom_config_field!(CustomConfigAngleField, len: REFLOAT_CONFIG_LEN, offset: 44, scale: 100.0);
    const DUTY_PUSHBACK_SPEED_FIELD: CustomConfigAngularVelocityField = vescpkg_rs::generated_custom_config_field!(CustomConfigAngularVelocityField, len: REFLOAT_CONFIG_LEN, offset: 46, scale: 100.0);
    const DUTY_PUSHBACK_THRESHOLD_FIELD: CustomConfigRatioField = vescpkg_rs::generated_custom_config_field!(CustomConfigRatioField, len: REFLOAT_CONFIG_LEN, offset: 48, scale: 1000.0);
    const DUTY_BEEP_ENABLED_FIELD: CustomConfigFlagField = vescpkg_rs::generated_custom_config_field!(CustomConfigFlagField, len: REFLOAT_CONFIG_LEN, offset: 50);
    const FOOT_BEEP_ENABLED_FIELD: CustomConfigFlagField = vescpkg_rs::generated_custom_config_field!(CustomConfigFlagField, len: REFLOAT_CONFIG_LEN, offset: 28);
    const TILTBACK_RETURN_SPEED_FIELD: CustomConfigAngularVelocityField = vescpkg_rs::generated_custom_config_field!(CustomConfigAngularVelocityField, len: REFLOAT_CONFIG_LEN, offset: 64, scale: 100.0);
    const PERSISTENT_FATAL_ERROR_FIELD: CustomConfigFlagField = vescpkg_rs::generated_custom_config_field!(CustomConfigFlagField, len: REFLOAT_CONFIG_LEN, offset: 66);
    const TILTBACK_CONSTANT_ANGLE_FIELD: CustomConfigAngleField = vescpkg_rs::generated_custom_config_field!(CustomConfigAngleField, len: REFLOAT_CONFIG_LEN, offset: 67, scale: 1000.0);
    const TILTBACK_CONSTANT_ERPM_FIELD: CustomConfigElectricalSpeedField = vescpkg_rs::generated_custom_config_field!(CustomConfigElectricalSpeedField, len: REFLOAT_CONFIG_LEN, offset: 69);
    const TILTBACK_VARIABLE_RATE_FIELD: CustomConfigPidScaleField = vescpkg_rs::generated_custom_config_field!(CustomConfigPidScaleField, len: REFLOAT_CONFIG_LEN, offset: 71, scale: 1000.0);
    const TILTBACK_VARIABLE_MAX_FIELD: CustomConfigAngleField = vescpkg_rs::generated_custom_config_field!(CustomConfigAngleField, len: REFLOAT_CONFIG_LEN, offset: 73, scale: 100.0);
    const TILTBACK_VARIABLE_ERPM_FIELD: CustomConfigElectricalSpeedField = vescpkg_rs::generated_custom_config_field!(CustomConfigElectricalSpeedField, len: REFLOAT_CONFIG_LEN, offset: 75);
    const NOSE_ANGLING_SPEED_FIELD: CustomConfigAngularVelocityField = vescpkg_rs::generated_custom_config_field!(CustomConfigAngularVelocityField, len: REFLOAT_CONFIG_LEN, offset: 77, scale: 100.0);
    const INPUT_TILT_REMOTE_TYPE_FIELD: CustomConfigWireByteField = vescpkg_rs::generated_custom_config_field!(CustomConfigWireByteField, len: REFLOAT_CONFIG_LEN, offset: 79);
    const INPUT_TILT_ANGLE_LIMIT_FIELD: CustomConfigAngleField = vescpkg_rs::generated_custom_config_field!(CustomConfigAngleField, len: REFLOAT_CONFIG_LEN, offset: 80, scale: 100.0);
    const INPUT_TILT_SPEED_FIELD: CustomConfigAngularVelocityField = vescpkg_rs::generated_custom_config_field!(CustomConfigAngularVelocityField, len: REFLOAT_CONFIG_LEN, offset: 82, scale: 100.0);
    #[cfg_attr(not(target_arch = "arm"), allow(dead_code))]
    const INPUT_TILT_INVERT_FIELD: CustomConfigFlagField = vescpkg_rs::generated_custom_config_field!(CustomConfigFlagField, len: REFLOAT_CONFIG_LEN, offset: 84);
    #[cfg_attr(not(target_arch = "arm"), allow(dead_code))]
    const INPUT_TILT_DEADBAND_FIELD: CustomConfigRatioField = vescpkg_rs::generated_custom_config_field!(CustomConfigRatioField, len: REFLOAT_CONFIG_LEN, offset: 85, scale: 10000.0);
    const HIGH_VOLTAGE_PUSHBACK_ANGLE_FIELD: CustomConfigAngleField = vescpkg_rs::generated_custom_config_field!(CustomConfigAngleField, len: REFLOAT_CONFIG_LEN, offset: 51, scale: 100.0);
    const HIGH_VOLTAGE_THRESHOLD_FIELD: CustomConfigScaledVoltageField = vescpkg_rs::generated_custom_config_field!(CustomConfigScaledVoltageField, len: REFLOAT_CONFIG_LEN, offset: 55, scale: 100.0);
    const LOW_VOLTAGE_PUSHBACK_ANGLE_FIELD: CustomConfigAngleField = vescpkg_rs::generated_custom_config_field!(CustomConfigAngleField, len: REFLOAT_CONFIG_LEN, offset: 57, scale: 100.0);
    const LOW_VOLTAGE_THRESHOLD_FIELD: CustomConfigScaledVoltageField = vescpkg_rs::generated_custom_config_field!(CustomConfigScaledVoltageField, len: REFLOAT_CONFIG_LEN, offset: 61, scale: 100.0);
    const SPEED_PUSHBACK_THRESHOLD_FIELD: CustomConfigWireByteField = vescpkg_rs::generated_custom_config_field!(CustomConfigWireByteField, len: REFLOAT_CONFIG_LEN, offset: 63);
    // Generated `is_beeper_enabled` follows the 18-byte hardware LED block
    // beginning at offset 224; upstream serializes it immediately before
    // `disabled` at offset 243 (`third_party/refloat/src/conf/settings.xml:4049-4064`).
    const BEEPER_ENABLED_FIELD: CustomConfigFlagField = vescpkg_rs::generated_custom_config_field!(CustomConfigFlagField, len: REFLOAT_CONFIG_LEN, offset: 242);

    // Generated `hardware.leds.mode` is the first field in the final hardware
    // block at `third_party/refloat/src/conf/settings.xml:4049-4064`.
    const HARDWARE_LED_MODE_FIELD: CustomConfigEnumField<RefloatHardwareLedMode> = vescpkg_rs::generated_custom_config_field!(
        CustomConfigEnumField<RefloatHardwareLedMode>,
        len: REFLOAT_CONFIG_LEN,
        offset: 224
    );

    pub(crate) const fn defaults() -> Self {
        Self(CustomConfigImage::new(REFLOAT_DEFAULT_CONFIG))
    }

    pub(crate) fn from_serialized(bytes: &[u8]) -> Option<Self> {
        // C map: `read_cfg_from_eeprom` and `set_cfg` both accept only
        // successfully deserialized Refloat config images at
        // `third_party/refloat/src/main.c:1178-1185` and
        // `third_party/refloat/src/main.c:2368-2386`.
        let bytes = <&[u8; REFLOAT_CONFIG_LEN]>::try_from(bytes).ok()?;
        bytes
            .starts_with(&REFLOAT_CONFIG_SIGNATURE_BYTES)
            .then_some(Self(CustomConfigImage::new(*bytes)))
    }

    pub(crate) const fn as_bytes(&self) -> &[u8; REFLOAT_CONFIG_LEN] {
        self.0.as_bytes()
    }

    pub(crate) fn reset_tune_defaults(&mut self) {
        let mut bytes = *self.as_bytes();
        for range in [4..18, 67..75, 77..79, 91..101, 102..118, 130..175] {
            bytes[range.clone()].copy_from_slice(&REFLOAT_DEFAULT_CONFIG[range]);
        }
        bytes[242] = REFLOAT_DEFAULT_CONFIG[242];
        self.0 = CustomConfigImage::new(bytes);
    }

    pub(crate) fn hardware_led_mode_id(&self) -> u8 {
        Self::HARDWARE_LED_MODE_FIELD
            .read(&self.0)
            .map_or(0, |mode| mode.0)
    }

    fn flag(&self, field: CustomConfigFlagField) -> bool {
        field.read(&self.0).unwrap_or(false)
    }

    pub(crate) const fn balance(&self) -> RefloatBalanceConfig<'_> {
        RefloatBalanceConfig(self)
    }

    pub(crate) const fn filter(&self) -> RefloatFilterConfig<'_> {
        RefloatFilterConfig(self)
    }

    pub(crate) const fn faults(&self) -> RefloatFaultConfig<'_> {
        RefloatFaultConfig(self)
    }

    pub(crate) const fn startup(&self) -> RefloatStartupConfig<'_> {
        RefloatStartupConfig(self)
    }

    pub(crate) const fn remote_throttle(&self) -> RefloatRemoteThrottleConfig<'_> {
        RefloatRemoteThrottleConfig(self)
    }

    pub(crate) const fn motor_control(&self) -> RefloatMotorControlConfig<'_> {
        RefloatMotorControlConfig(self)
    }

    pub(crate) const fn metadata(&self) -> RefloatMetadataConfig<'_> {
        RefloatMetadataConfig(self)
    }

    #[cfg(any(test, target_arch = "arm"))]
    pub(crate) const fn bms(&self) -> RefloatBmsConfig<'_> {
        RefloatBmsConfig(self)
    }

    #[cfg(any(test, target_arch = "arm"))]
    pub(crate) const fn haptic(&self) -> RefloatHapticConfig<'_> {
        RefloatHapticConfig(self)
    }

    #[cfg(test)]
    pub(crate) fn set_haptic_current_threshold(&mut self, threshold: Ratio) -> bool {
        let mut editor = self.editor();
        RefloatHapticConfig::CURRENT_THRESHOLD_FIELD
            .write(&mut editor, threshold)
            .is_some()
    }

    pub(crate) fn balance_loop_config(&self) -> LoopConfig {
        // C map: `configure(d)` consumes these generated `float_conf` fields to
        // drive the control loop and timing at `third_party/refloat/src/main.c:161-199`;
        // the serialized field order is pinned in `third_party/refloat/src/conf/settings.xml:3917-3981`.
        let balance = self.balance();
        LoopConfig {
            kp: balance.kp(),
            kp2: balance.kp2(),
            ki: balance.ki(),
            kp_brake: balance.kp_brake(),
            kp2_brake: balance.kp2_brake(),
            ki_limit: balance.ki_limit(),
            booster_angle: balance.booster_angle(),
            booster_ramp: balance.booster_ramp(),
            booster_current: balance.booster_current(),
            brkbooster_angle: balance.brake_booster_angle(),
            brkbooster_ramp: balance.brake_booster_ramp(),
            brkbooster_current: balance.brake_booster_current(),
            hertz: self.startup().sample_rate(),
        }
    }

    pub(crate) fn motor_current_filter_frequency(&self) -> vescpkg_rs::Frequency {
        generated_field(Self::ATR_FILTER_FIELD.read(self))
    }

    pub(crate) fn duty_pushback_angle(&self) -> AngleDegrees {
        generated_field(Self::DUTY_PUSHBACK_ANGLE_FIELD.read(self))
    }

    pub(crate) fn duty_pushback_threshold(&self) -> Ratio {
        generated_field(Self::DUTY_PUSHBACK_THRESHOLD_FIELD.read(self))
    }

    pub(crate) fn duty_beep_enabled(&self) -> bool {
        generated_field(Self::DUTY_BEEP_ENABLED_FIELD.read(self))
    }

    pub(crate) fn foot_beep_enabled(&self) -> bool {
        generated_field(Self::FOOT_BEEP_ENABLED_FIELD.read(self))
    }

    pub(crate) fn duty_pushback_speed(&self) -> AngularVelocity {
        generated_field(Self::DUTY_PUSHBACK_SPEED_FIELD.read(self))
    }

    pub(crate) fn tiltback_return_speed(&self) -> AngularVelocity {
        generated_field(Self::TILTBACK_RETURN_SPEED_FIELD.read(self))
    }

    pub(crate) fn persistent_fatal_error(&self) -> bool {
        self.flag(Self::PERSISTENT_FATAL_ERROR_FIELD)
    }

    pub(crate) fn high_voltage_pushback_angle(&self) -> AngleDegrees {
        generated_field(Self::HIGH_VOLTAGE_PUSHBACK_ANGLE_FIELD.read(self))
    }

    pub(crate) fn high_voltage_threshold(&self) -> Voltage {
        generated_field(Self::HIGH_VOLTAGE_THRESHOLD_FIELD.read(self))
    }

    pub(crate) fn low_voltage_pushback_angle(&self) -> AngleDegrees {
        generated_field(Self::LOW_VOLTAGE_PUSHBACK_ANGLE_FIELD.read(self))
    }

    pub(crate) fn low_voltage_threshold(&self) -> Voltage {
        generated_field(Self::LOW_VOLTAGE_THRESHOLD_FIELD.read(self))
    }

    pub(crate) fn speed_pushback_threshold(&self) -> Speed {
        generated_field(Self::SPEED_PUSHBACK_THRESHOLD_FIELD.read(self)).scaled(
            1.0,
            0.0,
            Speed::from_kilometers_per_hour,
        )
    }

    #[cfg_attr(not(target_arch = "arm"), allow(dead_code))]
    pub(crate) fn input_tilt_remote_type(&self) -> u8 {
        generated_field(Self::INPUT_TILT_REMOTE_TYPE_FIELD.read(self)).as_u8()
    }

    pub(crate) fn input_tilt_angle_limit(&self) -> AngleDegrees {
        generated_field(Self::INPUT_TILT_ANGLE_LIMIT_FIELD.read(self))
    }

    pub(crate) fn input_tilt_speed(&self) -> AngularVelocity {
        generated_field(Self::INPUT_TILT_SPEED_FIELD.read(self))
    }

    #[cfg_attr(not(target_arch = "arm"), allow(dead_code))]
    pub(crate) fn input_tilt_inverted(&self) -> bool {
        self.flag(Self::INPUT_TILT_INVERT_FIELD)
    }

    #[cfg_attr(not(target_arch = "arm"), allow(dead_code))]
    pub(crate) fn input_tilt_deadband(&self) -> Ratio {
        generated_field(Self::INPUT_TILT_DEADBAND_FIELD.read(self))
    }

    pub(crate) fn tiltback_constant(&self) -> AngleDegrees {
        generated_field(Self::TILTBACK_CONSTANT_ANGLE_FIELD.read(self))
    }

    pub(crate) fn tiltback_constant_erpm(&self) -> ElectricalSpeed {
        generated_field(Self::TILTBACK_CONSTANT_ERPM_FIELD.read(self))
    }

    pub(crate) fn tiltback_variable(&self) -> PidScale {
        generated_field(Self::TILTBACK_VARIABLE_RATE_FIELD.read(self))
    }

    pub(crate) fn tiltback_variable_max(&self) -> AngleDegrees {
        generated_field(Self::TILTBACK_VARIABLE_MAX_FIELD.read(self))
    }

    pub(crate) fn tiltback_variable_erpm(&self) -> ElectricalSpeed {
        generated_field(Self::TILTBACK_VARIABLE_ERPM_FIELD.read(self))
    }

    pub(crate) fn nose_angling_speed(&self) -> AngularVelocity {
        generated_field(Self::NOSE_ANGLING_SPEED_FIELD.read(self))
    }

    pub(crate) fn beeper_enabled(&self) -> bool {
        self.flag(Self::BEEPER_ENABLED_FIELD)
    }

    pub(crate) fn editor(&mut self) -> RefloatConfigEditor<'_> {
        RefloatConfigEditor(self.0.editor())
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(transparent)]
#[cfg(any(test, target_arch = "arm"))]
pub(crate) struct RefloatHapticConfig<'a>(&'a RefloatConfigImage);

#[cfg(any(test, target_arch = "arm"))]
impl RefloatHapticConfig<'_> {
    const DUTY_FREQUENCY_FIELD: CustomConfigFrequencyField = vescpkg_rs::generated_custom_config_field!(CustomConfigFrequencyField, len: REFLOAT_CONFIG_LEN, offset: 244, scale: 1.0);
    const DUTY_STRENGTH_FIELD: CustomConfigScaledVoltageField = vescpkg_rs::generated_custom_config_field!(CustomConfigScaledVoltageField, len: REFLOAT_CONFIG_LEN, offset: 246, scale: 10.0);
    const ERROR_FREQUENCY_FIELD: CustomConfigFrequencyField = vescpkg_rs::generated_custom_config_field!(CustomConfigFrequencyField, len: REFLOAT_CONFIG_LEN, offset: 248, scale: 1.0);
    const ERROR_STRENGTH_FIELD: CustomConfigScaledVoltageField = vescpkg_rs::generated_custom_config_field!(CustomConfigScaledVoltageField, len: REFLOAT_CONFIG_LEN, offset: 250, scale: 10.0);
    const VIBRATE_FREQUENCY_FIELD: CustomConfigFrequencyField = vescpkg_rs::generated_custom_config_field!(CustomConfigFrequencyField, len: REFLOAT_CONFIG_LEN, offset: 252, scale: 1.0);
    const VIBRATE_STRENGTH_FIELD: CustomConfigMotorCurrentField = vescpkg_rs::generated_custom_config_field!(CustomConfigMotorCurrentField, len: REFLOAT_CONFIG_LEN, offset: 254, scale: 10.0);
    const DUTY_SOLID_OFFSET_FIELD: CustomConfigRatioField = vescpkg_rs::generated_custom_config_field!(CustomConfigRatioField, len: REFLOAT_CONFIG_LEN, offset: 256, scale: 10000.0);
    const CURRENT_THRESHOLD_FIELD: CustomConfigRatioField = vescpkg_rs::generated_custom_config_field!(CustomConfigRatioField, len: REFLOAT_CONFIG_LEN, offset: 258, scale: 10000.0);
    const MIN_STRENGTH_FIELD: CustomConfigRatioField = vescpkg_rs::generated_custom_config_field!(CustomConfigRatioField, len: REFLOAT_CONFIG_LEN, offset: 260, scale: 10000.0);
    const MAX_STRENGTH_SPEED_FIELD: CustomConfigWireByteField = vescpkg_rs::generated_custom_config_field!(CustomConfigWireByteField, len: REFLOAT_CONFIG_LEN, offset: 262);
    const STRENGTH_CURVATURE_FIELD: CustomConfigRatioField = vescpkg_rs::generated_custom_config_field!(CustomConfigRatioField, len: REFLOAT_CONFIG_LEN, offset: 263, scale: 1000.0);

    pub(crate) fn duty_frequency(self) -> AudioFrequency {
        AudioFrequency::new(generated_field(Self::DUTY_FREQUENCY_FIELD.read(self.0)))
    }

    pub(crate) fn duty_strength(self) -> AudioVoltage {
        AudioVoltage::new(generated_field(Self::DUTY_STRENGTH_FIELD.read(self.0)))
    }

    pub(crate) fn error_frequency(self) -> AudioFrequency {
        AudioFrequency::new(generated_field(Self::ERROR_FREQUENCY_FIELD.read(self.0)))
    }

    pub(crate) fn error_strength(self) -> AudioVoltage {
        AudioVoltage::new(generated_field(Self::ERROR_STRENGTH_FIELD.read(self.0)))
    }

    pub(crate) fn vibrate_frequency(self) -> AudioFrequency {
        AudioFrequency::new(generated_field(Self::VIBRATE_FREQUENCY_FIELD.read(self.0)))
    }

    pub(crate) fn vibrate_strength(self) -> MotorCurrent {
        generated_field(Self::VIBRATE_STRENGTH_FIELD.read(self.0))
    }

    pub(crate) fn duty_solid_offset(self) -> Ratio {
        generated_field(Self::DUTY_SOLID_OFFSET_FIELD.read(self.0))
    }

    pub(crate) fn current_threshold(self) -> Ratio {
        generated_field(Self::CURRENT_THRESHOLD_FIELD.read(self.0))
    }

    pub(crate) fn min_strength(self) -> Ratio {
        generated_field(Self::MIN_STRENGTH_FIELD.read(self.0))
    }

    pub(crate) fn max_strength_speed(self) -> Speed {
        generated_field(Self::MAX_STRENGTH_SPEED_FIELD.read(self.0)).scaled(
            1.0,
            0.0,
            Speed::from_kilometers_per_hour,
        )
    }

    pub(crate) fn strength_curvature(self) -> Ratio {
        generated_field(Self::STRENGTH_CURVATURE_FIELD.read(self.0))
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct RefloatHardwareLedMode(u8);

impl From<u8> for RefloatHardwareLedMode {
    fn from(value: u8) -> Self {
        Self(value)
    }
}

pub(crate) struct RefloatConfigEditor<'a>(CustomConfigEditor<'a, REFLOAT_CONFIG_LEN>);

impl<'a> core::ops::Deref for RefloatConfigEditor<'a> {
    type Target = CustomConfigEditor<'a, REFLOAT_CONFIG_LEN>;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl core::ops::DerefMut for RefloatConfigEditor<'_> {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}

#[cfg_attr(test, allow(dead_code))]
impl RefloatConfigEditor<'_> {
    fn set_flag(&mut self, field: CustomConfigFlagField, value: bool) -> bool {
        field.write(&mut self.0, value).is_some()
    }

    pub(crate) fn clear_meta_is_default(&mut self) {
        // C map: `set_cfg` always clears `meta.is_default` after a write at
        // `third_party/refloat/src/main.c:2375-2377`.
        self.set_flag(RefloatMetadataConfig::IS_DEFAULT_FIELD, false);
    }

    #[cfg(test)]
    pub(crate) fn set_meta_is_default(&mut self, is_default: bool) -> bool {
        self.set_flag(RefloatMetadataConfig::IS_DEFAULT_FIELD, is_default)
    }

    pub(crate) fn keep_enabled_while_running(&mut self) {
        // C map: `set_cfg` refuses to persist package disablement while
        // RUNNING at `third_party/refloat/src/main.c:2370-2373`.
        self.set_flag(RefloatMetadataConfig::DISABLED_FIELD, false);
    }

    pub(crate) fn set_disabled(&mut self, disabled: bool) -> bool {
        self.set_flag(RefloatMetadataConfig::DISABLED_FIELD, disabled)
    }

    pub(crate) fn set_beeper_enabled(&mut self, enabled: bool) -> bool {
        self.set_flag(RefloatConfigImage::BEEPER_ENABLED_FIELD, enabled)
    }

    #[cfg(test)]
    pub(crate) fn set_hertz(&mut self, sample_rate: SampleRate) -> bool {
        RefloatStartupConfig::HERTZ_FIELD
            .write(self, sample_rate)
            .is_some()
    }

    pub(crate) fn set_startup_pitch_tolerance(&mut self, angle: AngleDegrees) -> bool {
        RefloatStartupConfig::PITCH_TOLERANCE_FIELD
            .write(self, angle)
            .is_some()
    }

    pub(crate) fn set_startup_roll_tolerance(&mut self, angle: AngleDegrees) -> bool {
        RefloatStartupConfig::ROLL_TOLERANCE_FIELD
            .write(self, angle)
            .is_some()
    }

    pub(crate) fn set_startup_speed(&mut self, speed: AngularVelocity) -> bool {
        RefloatStartupConfig::SPEED_FIELD
            .write(self, speed)
            .is_some()
    }

    pub(crate) fn set_pushstart_enabled(&mut self, enabled: bool) -> bool {
        self.set_flag(RefloatStartupConfig::PUSHSTART_FIELD, enabled)
    }

    pub(crate) fn set_simplestart_enabled(&mut self, enabled: bool) -> bool {
        self.set_flag(RefloatStartupConfig::SIMPLESTART_FIELD, enabled)
    }

    pub(crate) fn set_reversestop_enabled(&mut self, enabled: bool) -> bool {
        self.set_flag(RefloatFaultConfig::REVERSESTOP_FIELD, enabled)
    }

    #[cfg(test)]
    pub(crate) fn set_quickstop_enabled(&mut self, enabled: bool) -> bool {
        self.set_flag(RefloatFaultConfig::QUICKSTOP_FIELD, enabled)
    }

    pub(crate) fn set_darkride_enabled(&mut self, enabled: bool) -> bool {
        self.set_flag(RefloatFaultConfig::DARKRIDE_FIELD, enabled)
    }

    pub(crate) fn set_dual_switch(&mut self, enabled: bool) -> bool {
        self.set_flag(RefloatFaultConfig::DUAL_SWITCH_FIELD, enabled)
    }

    #[cfg(test)]
    pub(crate) fn set_remote_throttle_current_max(&mut self, current: MotorCurrent) -> bool {
        RefloatRemoteThrottleConfig::CURRENT_MAX_FIELD
            .write(self, current)
            .is_some()
    }

    #[cfg(test)]
    pub(crate) fn set_remote_throttle_grace_period(&mut self, duration: VescSeconds) -> bool {
        RefloatRemoteThrottleConfig::GRACE_PERIOD_FIELD
            .write(self, duration)
            .is_some()
    }

    pub(crate) fn set_kp(&mut self, kp: AngleCurrentGain) -> bool {
        RefloatBalanceConfig::KP_FIELD.write(self, kp).is_some()
    }

    pub(crate) fn set_kp2(&mut self, kp2: RateCurrentGain) -> bool {
        RefloatBalanceConfig::KP2_FIELD.write(self, kp2).is_some()
    }

    pub(crate) fn set_ki(&mut self, ki: IntegralCurrentGain) -> bool {
        RefloatBalanceConfig::KI_FIELD.write(self, ki).is_some()
    }

    pub(crate) fn set_kp_brake(&mut self, scale: PidScale) -> bool {
        RefloatBalanceConfig::KP_BRAKE_FIELD
            .write(self, scale)
            .is_some()
    }

    pub(crate) fn set_kp2_brake(&mut self, scale: PidScale) -> bool {
        RefloatBalanceConfig::KP2_BRAKE_FIELD
            .write(self, scale)
            .is_some()
    }

    pub(crate) fn set_ki_limit(&mut self, current: MotorCurrent) -> bool {
        let amps = current.current().as_amps();
        if !amps.is_finite() || amps < 0.0 {
            return false;
        }
        RefloatBalanceConfig::KI_LIMIT_FIELD
            .write(self, current)
            .is_some()
    }

    pub(crate) fn set_mahony_kp(&mut self, gain: MahonyPitchGain) -> bool {
        RefloatFilterConfig::MAHONY_KP_FIELD
            .write(self, gain)
            .is_some()
    }

    pub(crate) fn set_duty_beep_enabled(&mut self, enabled: bool) -> bool {
        self.set_flag(RefloatConfigImage::DUTY_BEEP_ENABLED_FIELD, enabled)
    }

    pub(crate) fn set_duty_pushback_angle(&mut self, angle: AngleDegrees) -> bool {
        RefloatConfigImage::DUTY_PUSHBACK_ANGLE_FIELD
            .write(self, angle)
            .is_some()
    }

    pub(crate) fn set_duty_pushback_speed(&mut self, speed: AngularVelocity) -> bool {
        RefloatConfigImage::DUTY_PUSHBACK_SPEED_FIELD
            .write(self, speed)
            .is_some()
    }

    pub(crate) fn set_duty_pushback_threshold(&mut self, threshold: Ratio) -> bool {
        RefloatConfigImage::DUTY_PUSHBACK_THRESHOLD_FIELD
            .write(self, threshold)
            .is_some()
    }

    pub(crate) fn set_tiltback_return_speed(&mut self, speed: AngularVelocity) -> bool {
        RefloatConfigImage::TILTBACK_RETURN_SPEED_FIELD
            .write(self, speed)
            .is_some()
    }

    #[cfg(test)]
    pub(crate) fn set_speed_pushback_threshold(&mut self, speed: vescpkg_rs::WireByte) -> bool {
        RefloatConfigImage::SPEED_PUSHBACK_THRESHOLD_FIELD
            .write(self, speed)
            .is_some()
    }

    pub(crate) fn set_dirty_landings_enabled(&mut self, enabled: bool) -> bool {
        self.set_flag(RefloatStartupConfig::DIRTY_LANDINGS_FIELD, enabled)
    }

    pub(crate) fn set_startup_click_current(&mut self, current: vescpkg_rs::WireByte) -> bool {
        RefloatStartupConfig::CLICK_CURRENT_FIELD
            .write(self, current)
            .is_some()
    }

    pub(crate) fn set_brake_current(&mut self, current: MotorCurrent) -> bool {
        RefloatMotorControlConfig::BRAKE_CURRENT_FIELD
            .write(self, current)
            .is_some()
    }

    pub(crate) fn set_tiltback_constant(&mut self, angle: AngleDegrees) -> bool {
        RefloatConfigImage::TILTBACK_CONSTANT_ANGLE_FIELD
            .write(self, angle)
            .is_some()
    }

    pub(crate) fn set_tiltback_constant_erpm(&mut self, erpm: ElectricalSpeed) -> bool {
        RefloatConfigImage::TILTBACK_CONSTANT_ERPM_FIELD
            .write(self, erpm)
            .is_some()
    }

    pub(crate) fn set_tiltback_variable(&mut self, rate: PidScale) -> bool {
        RefloatConfigImage::TILTBACK_VARIABLE_RATE_FIELD
            .write(self, rate)
            .is_some()
    }

    pub(crate) fn set_tiltback_variable_max(&mut self, angle: AngleDegrees) -> bool {
        RefloatConfigImage::TILTBACK_VARIABLE_MAX_FIELD
            .write(self, angle)
            .is_some()
    }

    pub(crate) fn set_tiltback_variable_erpm(&mut self, erpm: ElectricalSpeed) -> bool {
        RefloatConfigImage::TILTBACK_VARIABLE_ERPM_FIELD
            .write(self, erpm)
            .is_some()
    }

    pub(crate) fn set_nose_angling_speed(&mut self, speed: AngularVelocity) -> bool {
        RefloatConfigImage::NOSE_ANGLING_SPEED_FIELD
            .write(self, speed)
            .is_some()
    }

    pub(crate) fn set_input_tilt_remote_type(&mut self, remote: vescpkg_rs::WireByte) -> bool {
        RefloatConfigImage::INPUT_TILT_REMOTE_TYPE_FIELD
            .write(self, remote)
            .is_some()
    }

    pub(crate) fn set_input_tilt_angle_limit(&mut self, angle: AngleDegrees) -> bool {
        RefloatConfigImage::INPUT_TILT_ANGLE_LIMIT_FIELD
            .write(self, angle)
            .is_some()
    }

    pub(crate) fn set_input_tilt_speed(&mut self, speed: AngularVelocity) -> bool {
        RefloatConfigImage::INPUT_TILT_SPEED_FIELD
            .write(self, speed)
            .is_some()
    }

    #[cfg(test)]
    pub(crate) fn set_input_tilt_inverted(&mut self, inverted: bool) -> bool {
        self.set_flag(RefloatConfigImage::INPUT_TILT_INVERT_FIELD, inverted)
    }

    #[cfg(test)]
    pub(crate) fn set_input_tilt_deadband(&mut self, deadband: Ratio) -> bool {
        RefloatConfigImage::INPUT_TILT_DEADBAND_FIELD
            .write(self, deadband)
            .is_some()
    }

    pub(crate) fn set_booster_angle(&mut self, angle: AngleDegrees) -> bool {
        RefloatBalanceConfig::BOOSTER_ANGLE_FIELD
            .write(self, angle)
            .is_some()
    }

    pub(crate) fn set_booster_ramp(&mut self, angle: AngleDegrees) -> bool {
        RefloatBalanceConfig::BOOSTER_RAMP_FIELD
            .write(self, angle)
            .is_some()
    }

    pub(crate) fn set_booster_current(&mut self, current: MotorCurrent) -> bool {
        RefloatBalanceConfig::BOOSTER_CURRENT_FIELD
            .write(self, current)
            .is_some()
    }

    pub(crate) fn set_brake_booster_angle(&mut self, angle: AngleDegrees) -> bool {
        RefloatBalanceConfig::BRAKE_BOOSTER_ANGLE_FIELD
            .write(self, angle)
            .is_some()
    }

    pub(crate) fn set_brake_booster_ramp(&mut self, angle: AngleDegrees) -> bool {
        RefloatBalanceConfig::BRAKE_BOOSTER_RAMP_FIELD
            .write(self, angle)
            .is_some()
    }

    pub(crate) fn set_brake_booster_current(&mut self, current: MotorCurrent) -> bool {
        RefloatBalanceConfig::BRAKE_BOOSTER_CURRENT_FIELD
            .write(self, current)
            .is_some()
    }

    pub(crate) fn set_torque_tilt_start_current(&mut self, current: MotorCurrent) -> bool {
        RefloatBalanceConfig::TORQUE_TILT_START_CURRENT_FIELD
            .write(self, current)
            .is_some()
    }

    pub(crate) fn set_torque_tilt_angle_limit(&mut self, angle: AngleDegrees) -> bool {
        RefloatBalanceConfig::TORQUE_TILT_ANGLE_LIMIT_FIELD
            .write(self, angle)
            .is_some()
    }

    pub(crate) fn set_torque_tilt_on_speed(&mut self, speed: AngularVelocity) -> bool {
        RefloatBalanceConfig::TORQUE_TILT_ON_SPEED_FIELD
            .write(self, speed)
            .is_some()
    }

    pub(crate) fn set_torque_tilt_off_speed(&mut self, speed: AngularVelocity) -> bool {
        RefloatBalanceConfig::TORQUE_TILT_OFF_SPEED_FIELD
            .write(self, speed)
            .is_some()
    }

    pub(crate) fn set_torque_tilt_strength(&mut self, strength: PidScale) -> bool {
        RefloatBalanceConfig::TORQUE_TILT_STRENGTH_FIELD
            .write(self, strength)
            .is_some()
    }

    pub(crate) fn set_torque_tilt_regen_strength(&mut self, strength: PidScale) -> bool {
        RefloatBalanceConfig::TORQUE_TILT_REGEN_STRENGTH_FIELD
            .write(self, strength)
            .is_some()
    }

    pub(crate) fn set_turn_tilt_strength(&mut self, strength: PidScale) -> bool {
        RefloatBalanceConfig::TURN_TILT_STRENGTH_FIELD
            .write(self, strength)
            .is_some()
    }

    pub(crate) fn set_turn_tilt_angle_limit(&mut self, angle: AngleDegrees) -> bool {
        RefloatBalanceConfig::TURN_TILT_ANGLE_LIMIT_FIELD
            .write(self, angle)
            .is_some()
    }

    pub(crate) fn set_turn_tilt_start_erpm(&mut self, speed: ElectricalSpeed) -> bool {
        RefloatBalanceConfig::TURN_TILT_START_ERPM_FIELD
            .write(self, speed)
            .is_some()
    }

    pub(crate) fn set_atr_strength_up(&mut self, strength: PidScale) -> bool {
        RefloatBalanceConfig::ATR_STRENGTH_UP_FIELD
            .write(self, strength)
            .is_some()
    }

    pub(crate) fn set_atr_strength_down(&mut self, strength: PidScale) -> bool {
        RefloatBalanceConfig::ATR_STRENGTH_DOWN_FIELD
            .write(self, strength)
            .is_some()
    }

    pub(crate) fn set_atr_threshold_up(&mut self, angle: AngleDegrees) -> bool {
        RefloatBalanceConfig::ATR_THRESHOLD_UP_FIELD
            .write(self, angle)
            .is_some()
    }

    pub(crate) fn set_atr_threshold_down(&mut self, angle: AngleDegrees) -> bool {
        RefloatBalanceConfig::ATR_THRESHOLD_DOWN_FIELD
            .write(self, angle)
            .is_some()
    }

    pub(crate) fn set_atr_speed_boost(&mut self, strength: PidScale) -> bool {
        RefloatBalanceConfig::ATR_SPEED_BOOST_FIELD
            .write(self, strength)
            .is_some()
    }

    pub(crate) fn set_atr_angle_limit(&mut self, angle: AngleDegrees) -> bool {
        RefloatBalanceConfig::ATR_ANGLE_LIMIT_FIELD
            .write(self, angle)
            .is_some()
    }

    pub(crate) fn set_atr_on_speed(&mut self, speed: AngularVelocity) -> bool {
        RefloatBalanceConfig::ATR_ON_SPEED_FIELD
            .write(self, speed)
            .is_some()
    }

    pub(crate) fn set_atr_off_speed(&mut self, speed: AngularVelocity) -> bool {
        RefloatBalanceConfig::ATR_OFF_SPEED_FIELD
            .write(self, speed)
            .is_some()
    }

    pub(crate) fn set_atr_response_boost(&mut self, strength: PidScale) -> bool {
        RefloatBalanceConfig::ATR_RESPONSE_BOOST_FIELD
            .write(self, strength)
            .is_some()
    }

    pub(crate) fn set_atr_transition_boost(&mut self, strength: PidScale) -> bool {
        RefloatBalanceConfig::ATR_TRANSITION_BOOST_FIELD
            .write(self, strength)
            .is_some()
    }

    pub(crate) fn set_atr_amps_accel_ratio(&mut self, ratio: PidScale) -> bool {
        RefloatBalanceConfig::ATR_AMPS_ACCEL_RATIO_FIELD
            .write(self, ratio)
            .is_some()
    }

    pub(crate) fn set_atr_amps_decel_ratio(&mut self, ratio: PidScale) -> bool {
        RefloatBalanceConfig::ATR_AMPS_DECEL_RATIO_FIELD
            .write(self, ratio)
            .is_some()
    }

    pub(crate) fn set_brake_tilt_strength(&mut self, strength: PidScale) -> bool {
        RefloatBalanceConfig::BRAKE_TILT_STRENGTH_FIELD
            .write(self, strength)
            .is_some()
    }

    pub(crate) fn set_brake_tilt_lingering(&mut self, lingering: PidScale) -> bool {
        RefloatBalanceConfig::BRAKE_TILT_LINGERING_FIELD
            .write(self, lingering)
            .is_some()
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(transparent)]
pub(crate) struct RefloatMetadataConfig<'a>(&'a RefloatConfigImage);

impl RefloatMetadataConfig<'_> {
    // Upstream defines `disabled` in `third_party/refloat/src/conf/settings.xml:3890-3902`;
    // its `<ser>disabled</ser>` entry at `third_party/refloat/src/conf/settings.xml:4064`.
    const DISABLED_FIELD: CustomConfigFlagField = vescpkg_rs::generated_custom_config_field!(CustomConfigFlagField, len: REFLOAT_CONFIG_LEN, offset: 243);
    // Upstream defines `meta.is_default` in `third_party/refloat/src/conf/settings.xml:3903-3914`;
    // its `<ser>meta.is_default</ser>` entry at `third_party/refloat/src/conf/settings.xml:4083`.
    const IS_DEFAULT_FIELD: CustomConfigFlagField = vescpkg_rs::generated_custom_config_field!(CustomConfigFlagField, len: REFLOAT_CONFIG_LEN, offset: 275);

    pub(crate) fn disabled(self) -> bool {
        self.0.flag(Self::DISABLED_FIELD)
    }

    #[cfg(test)]
    pub(crate) fn is_default(self) -> bool {
        self.0.flag(Self::IS_DEFAULT_FIELD)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(transparent)]
#[cfg(any(test, target_arch = "arm"))]
pub(crate) struct RefloatBmsConfig<'a>(&'a RefloatConfigImage);

#[cfg(any(test, target_arch = "arm"))]
impl RefloatBmsConfig<'_> {
    // Generated Refloat v1.2.1 serialization places `bms.enabled` after the
    // haptic fields and before the six BMS thresholds at
    // `third_party/refloat/src/conf/settings.xml:4076-4082`.
    const ENABLED_FIELD: CustomConfigFlagField = vescpkg_rs::generated_custom_config_field!(
        CustomConfigFlagField,
        len: REFLOAT_CONFIG_LEN,
        offset: 265
    );
    const CELL_LOW_VOLTAGE_FIELD: CustomConfigScaledVoltageField = vescpkg_rs::generated_custom_config_field!(
        CustomConfigScaledVoltageField,
        len: REFLOAT_CONFIG_LEN,
        offset: 266,
        scale: 1000.0
    );
    const CELL_HIGH_VOLTAGE_FIELD: CustomConfigScaledVoltageField = vescpkg_rs::generated_custom_config_field!(
        CustomConfigScaledVoltageField,
        len: REFLOAT_CONFIG_LEN,
        offset: 268,
        scale: 1000.0
    );
    const CELL_BALANCE_VOLTAGE_FIELD: CustomConfigScaledVoltageField = vescpkg_rs::generated_custom_config_field!(
        CustomConfigScaledVoltageField,
        len: REFLOAT_CONFIG_LEN,
        offset: 270,
        scale: 1000.0
    );
    const CELL_HIGH_TEMPERATURE_OFFSET: usize = 272;
    const CELL_LOW_TEMPERATURE_OFFSET: usize = 273;
    const BMS_HIGH_TEMPERATURE_OFFSET: usize = 274;

    pub(crate) fn enabled(self) -> bool {
        self.0.flag(Self::ENABLED_FIELD)
    }

    pub(crate) fn thresholds(self) -> RefloatBmsThresholds {
        RefloatBmsThresholds::new(
            generated_field(Self::CELL_LOW_VOLTAGE_FIELD.read(self.0)),
            generated_field(Self::CELL_HIGH_VOLTAGE_FIELD.read(self.0)),
            generated_field(Self::CELL_BALANCE_VOLTAGE_FIELD.read(self.0)),
            RefloatBmsTemperature::from_config_byte(
                self.0.as_bytes()[Self::CELL_LOW_TEMPERATURE_OFFSET],
            ),
            RefloatBmsTemperature::from_config_byte(
                self.0.as_bytes()[Self::CELL_HIGH_TEMPERATURE_OFFSET],
            ),
            RefloatBmsTemperature::from_config_byte(
                self.0.as_bytes()[Self::BMS_HIGH_TEMPERATURE_OFFSET],
            ),
        )
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum RefloatParkingBrakeMode {
    Always,
    Idle,
    Never,
    Unknown(u8),
}

impl From<u8> for RefloatParkingBrakeMode {
    fn from(value: u8) -> Self {
        match value {
            0 => Self::Always,
            1 => Self::Idle,
            2 => Self::Never,
            value => Self::Unknown(value),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(transparent)]
pub(crate) struct RefloatMotorControlConfig<'a>(&'a RefloatConfigImage);

impl RefloatMotorControlConfig<'_> {
    // Upstream serializes default parking brake mode and brake current at
    // `third_party/refloat/src/conf/settings.xml:3973-3974`.
    const PARKING_BRAKE_MODE_FIELD: CustomConfigEnumField<RefloatParkingBrakeMode> = vescpkg_rs::generated_custom_config_field!(
        CustomConfigEnumField<RefloatParkingBrakeMode>,
        len: REFLOAT_CONFIG_LEN,
        offset: 101
    );
    const BRAKE_CURRENT_FIELD: CustomConfigMotorCurrentField = vescpkg_rs::generated_custom_config_field!(CustomConfigMotorCurrentField, len: REFLOAT_CONFIG_LEN, offset: 102, scale: 100.0);

    pub(crate) fn parking_brake_mode(self) -> RefloatParkingBrakeMode {
        Self::PARKING_BRAKE_MODE_FIELD
            .read(self.0)
            .unwrap_or(RefloatParkingBrakeMode::Always)
    }

    pub(crate) fn brake_current(self) -> MotorCurrent {
        generated_field(Self::BRAKE_CURRENT_FIELD.read(self.0))
    }
}

#[derive(Debug, Clone, Copy, PartialEq)]
#[repr(transparent)]
pub(crate) struct RefloatFilterConfig<'a>(&'a RefloatConfigImage);

impl RefloatFilterConfig<'_> {
    // Upstream serializes Mahony pitch/roll KP after `ki` at
    // `third_party/refloat/src/conf/settings.xml:3916-3921`; both use scale 10000.
    const MAHONY_KP_FIELD: CustomConfigMahonyPitchGainField = vescpkg_rs::generated_custom_config_field!(CustomConfigMahonyPitchGainField, len: REFLOAT_CONFIG_LEN, offset: 10, scale: 10000.0);
    const MAHONY_KP_ROLL_FIELD: CustomConfigMahonyRollGainField = vescpkg_rs::generated_custom_config_field!(CustomConfigMahonyRollGainField, len: REFLOAT_CONFIG_LEN, offset: 12, scale: 10000.0);

    pub(crate) fn mahony_kp(self) -> MahonyPitchGain {
        generated_field(Self::MAHONY_KP_FIELD.read(self.0))
    }

    pub(crate) fn mahony_kp_roll(self) -> MahonyRollGain {
        generated_field(Self::MAHONY_KP_ROLL_FIELD.read(self.0))
    }
}

#[derive(Debug, Clone, Copy, PartialEq)]
#[repr(transparent)]
pub(crate) struct RefloatFaultConfig<'a>(&'a RefloatConfigImage);

impl RefloatFaultConfig<'_> {
    // Upstream serializes fault angles, ADC thresholds, delays, ERPM gates,
    // and feature flags at `third_party/refloat/src/conf/settings.xml:3925-3939`.
    const PITCH_FIELD: CustomConfigAngleField = vescpkg_rs::generated_custom_config_field!(CustomConfigAngleField, len: REFLOAT_CONFIG_LEN, offset: 20, scale: 10.0);
    const ROLL_FIELD: CustomConfigAngleField = vescpkg_rs::generated_custom_config_field!(CustomConfigAngleField, len: REFLOAT_CONFIG_LEN, offset: 22, scale: 10.0);
    #[cfg(any(test, target_arch = "arm"))]
    const ADC1_FIELD: CustomConfigVoltageField = vescpkg_rs::generated_custom_config_field!(CustomConfigVoltageField, len: REFLOAT_CONFIG_LEN, offset: 24);
    #[cfg(any(test, target_arch = "arm"))]
    const ADC2_FIELD: CustomConfigVoltageField = vescpkg_rs::generated_custom_config_field!(CustomConfigVoltageField, len: REFLOAT_CONFIG_LEN, offset: 26);
    const DELAY_PITCH_OFFSET: usize = 29;
    const DELAY_ROLL_OFFSET: usize = 31;
    const DELAY_PITCH_FIELD: CustomConfigDurationField = vescpkg_rs::generated_custom_config_field!(CustomConfigDurationField, len: REFLOAT_CONFIG_LEN, offset: Self::DELAY_PITCH_OFFSET);
    const DELAY_ROLL_FIELD: CustomConfigDurationField = vescpkg_rs::generated_custom_config_field!(CustomConfigDurationField, len: REFLOAT_CONFIG_LEN, offset: Self::DELAY_ROLL_OFFSET);
    const DELAY_SWITCH_HALF_FIELD: CustomConfigDurationField = vescpkg_rs::generated_custom_config_field!(CustomConfigDurationField, len: REFLOAT_CONFIG_LEN, offset: 33);
    const DELAY_SWITCH_FULL_FIELD: CustomConfigDurationField = vescpkg_rs::generated_custom_config_field!(CustomConfigDurationField, len: REFLOAT_CONFIG_LEN, offset: 35);
    const ADC_HALF_ERPM_FIELD: CustomConfigElectricalSpeedField = vescpkg_rs::generated_custom_config_field!(CustomConfigElectricalSpeedField, len: REFLOAT_CONFIG_LEN, offset: 37);
    const DUAL_SWITCH_FIELD: CustomConfigFlagField = vescpkg_rs::generated_custom_config_field!(CustomConfigFlagField, len: REFLOAT_CONFIG_LEN, offset: 39);
    const MOVING_FAULT_DISABLED_FIELD: CustomConfigFlagField = vescpkg_rs::generated_custom_config_field!(CustomConfigFlagField, len: REFLOAT_CONFIG_LEN, offset: 40);
    const QUICKSTOP_FIELD: CustomConfigFlagField = vescpkg_rs::generated_custom_config_field!(CustomConfigFlagField, len: REFLOAT_CONFIG_LEN, offset: 41);
    const DARKRIDE_FIELD: CustomConfigFlagField = vescpkg_rs::generated_custom_config_field!(CustomConfigFlagField, len: REFLOAT_CONFIG_LEN, offset: 42);
    const REVERSESTOP_FIELD: CustomConfigFlagField = vescpkg_rs::generated_custom_config_field!(CustomConfigFlagField, len: REFLOAT_CONFIG_LEN, offset: 43);

    fn delay_at(self, field: CustomConfigDurationField) -> VescSeconds {
        generated_field(field.read(self.0))
    }

    #[cfg(any(test, target_arch = "arm"))]
    pub(crate) fn adc1_voltage(self) -> vescpkg_rs::Voltage {
        generated_field(Self::ADC1_FIELD.read(self.0))
    }

    #[cfg(any(test, target_arch = "arm"))]
    pub(crate) fn adc2_voltage(self) -> vescpkg_rs::Voltage {
        generated_field(Self::ADC2_FIELD.read(self.0))
    }

    pub(crate) fn quickstop_enabled(self) -> bool {
        self.0.flag(Self::QUICKSTOP_FIELD)
    }

    pub(crate) fn dual_switch(self) -> bool {
        self.0.flag(Self::DUAL_SWITCH_FIELD)
    }

    pub(crate) fn adc_half_erpm(self) -> ElectricalSpeed {
        generated_field(Self::ADC_HALF_ERPM_FIELD.read(self.0))
    }

    pub(crate) fn switch_half_delay(self) -> VescSeconds {
        self.delay_at(Self::DELAY_SWITCH_HALF_FIELD)
    }

    pub(crate) fn switch_full_delay(self) -> VescSeconds {
        self.delay_at(Self::DELAY_SWITCH_FULL_FIELD)
    }

    pub(crate) fn moving_faults_disabled(self) -> bool {
        self.0.flag(Self::MOVING_FAULT_DISABLED_FIELD)
    }

    pub(crate) fn roll_angle(self) -> AngleDegrees {
        generated_field(Self::ROLL_FIELD.read(self.0))
    }

    pub(crate) fn roll_delay(self) -> VescSeconds {
        self.delay_at(Self::DELAY_ROLL_FIELD)
    }

    pub(crate) fn pitch_angle(self) -> AngleDegrees {
        generated_field(Self::PITCH_FIELD.read(self.0))
    }

    pub(crate) fn pitch_delay(self) -> VescSeconds {
        self.delay_at(Self::DELAY_PITCH_FIELD)
    }

    pub(crate) fn darkride_enabled(self) -> bool {
        self.0.flag(Self::DARKRIDE_FIELD)
    }

    pub(crate) fn reversestop_enabled(self) -> bool {
        self.0.flag(Self::REVERSESTOP_FIELD)
    }
}

#[derive(Debug, Clone, Copy, PartialEq)]
#[repr(transparent)]
pub(crate) struct RefloatStartupConfig<'a>(&'a RefloatConfigImage);

impl RefloatStartupConfig<'_> {
    // Upstream defines `hertz` at `third_party/refloat/src/conf/settings.xml:223-246`,
    // then serializes startup tolerances/speed/flags at
    // `third_party/refloat/src/conf/settings.xml:3966-3972`.
    const HERTZ_FIELD: CustomConfigSampleRateField = vescpkg_rs::generated_custom_config_field!(CustomConfigSampleRateField, len: REFLOAT_CONFIG_LEN, offset: 18);
    const CLICK_CURRENT_FIELD: CustomConfigWireByteField = vescpkg_rs::generated_custom_config_field!(CustomConfigWireByteField, len: REFLOAT_CONFIG_LEN, offset: 97);
    const SIMPLESTART_FIELD: CustomConfigFlagField = vescpkg_rs::generated_custom_config_field!(CustomConfigFlagField, len: REFLOAT_CONFIG_LEN, offset: 98);
    const PUSHSTART_FIELD: CustomConfigFlagField = vescpkg_rs::generated_custom_config_field!(CustomConfigFlagField, len: REFLOAT_CONFIG_LEN, offset: 99);
    const DIRTY_LANDINGS_FIELD: CustomConfigFlagField = vescpkg_rs::generated_custom_config_field!(CustomConfigFlagField, len: REFLOAT_CONFIG_LEN, offset: 100);
    const PITCH_TOLERANCE_FIELD: CustomConfigAngleField = vescpkg_rs::generated_custom_config_field!(CustomConfigAngleField, len: REFLOAT_CONFIG_LEN, offset: 91, scale: 100.0);
    const ROLL_TOLERANCE_FIELD: CustomConfigAngleField = vescpkg_rs::generated_custom_config_field!(CustomConfigAngleField, len: REFLOAT_CONFIG_LEN, offset: 93, scale: 100.0);
    const SPEED_FIELD: CustomConfigAngularVelocityField = vescpkg_rs::generated_custom_config_field!(CustomConfigAngularVelocityField, len: REFLOAT_CONFIG_LEN, offset: 95, scale: 100.0);

    pub(crate) fn sample_rate(self) -> SampleRate {
        generated_field(Self::HERTZ_FIELD.read(self.0))
    }

    #[cfg(any(test, target_arch = "arm"))]
    pub(crate) fn loop_time_us(self) -> u32 {
        (1_000_000.0 / self.sample_rate().as_hertz().max(1.0)) as u32
    }

    pub(crate) fn simplestart_enabled(self) -> bool {
        self.0.flag(Self::SIMPLESTART_FIELD)
    }

    pub(crate) fn pitch_tolerance(self) -> AngleDegrees {
        generated_field(Self::PITCH_TOLERANCE_FIELD.read(self.0))
    }

    pub(crate) fn roll_tolerance(self) -> AngleDegrees {
        generated_field(Self::ROLL_TOLERANCE_FIELD.read(self.0))
    }

    pub(crate) fn pushstart_enabled(self) -> bool {
        self.0.flag(Self::PUSHSTART_FIELD)
    }

    pub(crate) fn startup_speed(self) -> AngularVelocity {
        generated_field(Self::SPEED_FIELD.read(self.0))
    }

    pub(crate) fn centering_step(self) -> AngleDegrees {
        let Some(period) = self.sample_rate().sample_period() else {
            return AngleDegrees::from_degrees(0.0);
        };
        AngleDegrees::from(self.startup_speed() * period)
    }
}

#[derive(Debug, Clone, Copy, PartialEq)]
#[repr(transparent)]
pub(crate) struct RefloatBalanceConfig<'a>(&'a RefloatConfigImage);

impl RefloatBalanceConfig<'_> {
    // Upstream serializes balance tuning fields in
    // `third_party/refloat/src/conf/settings.xml:3916-3923,3975-3984`.
    const KP_FIELD: CustomConfigAngleCurrentGainField = vescpkg_rs::generated_custom_config_field!(CustomConfigAngleCurrentGainField, len: REFLOAT_CONFIG_LEN, offset: 4, scale: 10.0);
    const KP2_FIELD: CustomConfigRateCurrentGainField = vescpkg_rs::generated_custom_config_field!(CustomConfigRateCurrentGainField, len: REFLOAT_CONFIG_LEN, offset: 6, scale: 100.0);
    const KI_FIELD: CustomConfigIntegralCurrentGainField = vescpkg_rs::generated_custom_config_field!(CustomConfigIntegralCurrentGainField, len: REFLOAT_CONFIG_LEN, offset: 8, scale: 100_000.0);
    const KP_BRAKE_FIELD: CustomConfigPidScaleField = vescpkg_rs::generated_custom_config_field!(CustomConfigPidScaleField, len: REFLOAT_CONFIG_LEN, offset: 14, scale: 100.0);
    const KP2_BRAKE_FIELD: CustomConfigPidScaleField = vescpkg_rs::generated_custom_config_field!(CustomConfigPidScaleField, len: REFLOAT_CONFIG_LEN, offset: 16, scale: 100.0);
    const KI_LIMIT_FIELD: CustomConfigMotorCurrentField = vescpkg_rs::generated_custom_config_field!(CustomConfigMotorCurrentField, len: REFLOAT_CONFIG_LEN, offset: 104, scale: 10.0);
    const BOOSTER_ANGLE_FIELD: CustomConfigAngleField = vescpkg_rs::generated_custom_config_field!(CustomConfigAngleField, len: REFLOAT_CONFIG_LEN, offset: 106, scale: 100.0);
    const BOOSTER_RAMP_FIELD: CustomConfigAngleField = vescpkg_rs::generated_custom_config_field!(CustomConfigAngleField, len: REFLOAT_CONFIG_LEN, offset: 108, scale: 100.0);
    const BOOSTER_CURRENT_FIELD: CustomConfigMotorCurrentField = vescpkg_rs::generated_custom_config_field!(CustomConfigMotorCurrentField, len: REFLOAT_CONFIG_LEN, offset: 110, scale: 100.0);
    const BRAKE_BOOSTER_ANGLE_FIELD: CustomConfigAngleField = vescpkg_rs::generated_custom_config_field!(CustomConfigAngleField, len: REFLOAT_CONFIG_LEN, offset: 112, scale: 100.0);
    const BRAKE_BOOSTER_RAMP_FIELD: CustomConfigAngleField = vescpkg_rs::generated_custom_config_field!(CustomConfigAngleField, len: REFLOAT_CONFIG_LEN, offset: 114, scale: 100.0);
    const BRAKE_BOOSTER_CURRENT_FIELD: CustomConfigMotorCurrentField = vescpkg_rs::generated_custom_config_field!(CustomConfigMotorCurrentField, len: REFLOAT_CONFIG_LEN, offset: 116, scale: 100.0);
    const TORQUE_TILT_START_CURRENT_FIELD: CustomConfigMotorCurrentField = vescpkg_rs::generated_custom_config_field!(CustomConfigMotorCurrentField, len: REFLOAT_CONFIG_LEN, offset: 118, scale: 100.0);
    const TORQUE_TILT_ANGLE_LIMIT_FIELD: CustomConfigAngleField = vescpkg_rs::generated_custom_config_field!(CustomConfigAngleField, len: REFLOAT_CONFIG_LEN, offset: 120, scale: 100.0);
    const TORQUE_TILT_ON_SPEED_FIELD: CustomConfigAngularVelocityField = vescpkg_rs::generated_custom_config_field!(CustomConfigAngularVelocityField, len: REFLOAT_CONFIG_LEN, offset: 122, scale: 100.0);
    const TORQUE_TILT_OFF_SPEED_FIELD: CustomConfigAngularVelocityField = vescpkg_rs::generated_custom_config_field!(CustomConfigAngularVelocityField, len: REFLOAT_CONFIG_LEN, offset: 124, scale: 100.0);
    const TORQUE_TILT_STRENGTH_FIELD: CustomConfigPidScaleField = vescpkg_rs::generated_custom_config_field!(CustomConfigPidScaleField, len: REFLOAT_CONFIG_LEN, offset: 126, scale: 1000.0);
    const TORQUE_TILT_REGEN_STRENGTH_FIELD: CustomConfigPidScaleField = vescpkg_rs::generated_custom_config_field!(CustomConfigPidScaleField, len: REFLOAT_CONFIG_LEN, offset: 128, scale: 1000.0);
    const TURN_TILT_STRENGTH_FIELD: CustomConfigPidScaleField = vescpkg_rs::generated_custom_config_field!(CustomConfigPidScaleField, len: REFLOAT_CONFIG_LEN, offset: 130, scale: 100.0);
    const TURN_TILT_ANGLE_LIMIT_FIELD: CustomConfigAngleField = vescpkg_rs::generated_custom_config_field!(CustomConfigAngleField, len: REFLOAT_CONFIG_LEN, offset: 132, scale: 100.0);
    const TURN_TILT_START_ANGLE_FIELD: CustomConfigAngleField = vescpkg_rs::generated_custom_config_field!(CustomConfigAngleField, len: REFLOAT_CONFIG_LEN, offset: 134, scale: 100.0);
    const TURN_TILT_START_ERPM_FIELD: CustomConfigElectricalSpeedField = vescpkg_rs::generated_custom_config_field!(CustomConfigElectricalSpeedField, len: REFLOAT_CONFIG_LEN, offset: 136);
    const TURN_TILT_SPEED_FIELD: CustomConfigAngularVelocityField = vescpkg_rs::generated_custom_config_field!(CustomConfigAngularVelocityField, len: REFLOAT_CONFIG_LEN, offset: 138, scale: 100.0);
    const ATR_STRENGTH_UP_FIELD: CustomConfigPidScaleField = vescpkg_rs::generated_custom_config_field!(CustomConfigPidScaleField, len: REFLOAT_CONFIG_LEN, offset: 145, scale: 1000.0);
    const ATR_STRENGTH_DOWN_FIELD: CustomConfigPidScaleField = vescpkg_rs::generated_custom_config_field!(CustomConfigPidScaleField, len: REFLOAT_CONFIG_LEN, offset: 147, scale: 1000.0);
    const ATR_THRESHOLD_UP_FIELD: CustomConfigAngleField = vescpkg_rs::generated_custom_config_field!(CustomConfigAngleField, len: REFLOAT_CONFIG_LEN, offset: 149, scale: 100.0);
    const ATR_THRESHOLD_DOWN_FIELD: CustomConfigAngleField = vescpkg_rs::generated_custom_config_field!(CustomConfigAngleField, len: REFLOAT_CONFIG_LEN, offset: 151, scale: 100.0);
    const ATR_SPEED_BOOST_FIELD: CustomConfigPidScaleField = vescpkg_rs::generated_custom_config_field!(CustomConfigPidScaleField, len: REFLOAT_CONFIG_LEN, offset: 153, scale: 10000.0);
    const ATR_ANGLE_LIMIT_FIELD: CustomConfigAngleField = vescpkg_rs::generated_custom_config_field!(CustomConfigAngleField, len: REFLOAT_CONFIG_LEN, offset: 155, scale: 100.0);
    const ATR_ON_SPEED_FIELD: CustomConfigAngularVelocityField = vescpkg_rs::generated_custom_config_field!(CustomConfigAngularVelocityField, len: REFLOAT_CONFIG_LEN, offset: 157, scale: 100.0);
    const ATR_OFF_SPEED_FIELD: CustomConfigAngularVelocityField = vescpkg_rs::generated_custom_config_field!(CustomConfigAngularVelocityField, len: REFLOAT_CONFIG_LEN, offset: 159, scale: 100.0);
    const ATR_RESPONSE_BOOST_FIELD: CustomConfigPidScaleField = vescpkg_rs::generated_custom_config_field!(CustomConfigPidScaleField, len: REFLOAT_CONFIG_LEN, offset: 161, scale: 1000.0);
    const ATR_TRANSITION_BOOST_FIELD: CustomConfigPidScaleField = vescpkg_rs::generated_custom_config_field!(CustomConfigPidScaleField, len: REFLOAT_CONFIG_LEN, offset: 163, scale: 1000.0);
    const ATR_AMPS_ACCEL_RATIO_FIELD: CustomConfigPidScaleField = vescpkg_rs::generated_custom_config_field!(CustomConfigPidScaleField, len: REFLOAT_CONFIG_LEN, offset: 167, scale: 100.0);
    const ATR_AMPS_DECEL_RATIO_FIELD: CustomConfigPidScaleField = vescpkg_rs::generated_custom_config_field!(CustomConfigPidScaleField, len: REFLOAT_CONFIG_LEN, offset: 169, scale: 100.0);
    const BRAKE_TILT_STRENGTH_FIELD: CustomConfigPidScaleField = vescpkg_rs::generated_custom_config_field!(CustomConfigPidScaleField, len: REFLOAT_CONFIG_LEN, offset: 171, scale: 100.0);
    const BRAKE_TILT_LINGERING_FIELD: CustomConfigPidScaleField = vescpkg_rs::generated_custom_config_field!(CustomConfigPidScaleField, len: REFLOAT_CONFIG_LEN, offset: 173, scale: 1000.0);

    pub(crate) fn kp(self) -> AngleCurrentGain {
        generated_field(Self::KP_FIELD.read(self.0))
    }

    pub(crate) fn kp2(self) -> RateCurrentGain {
        generated_field(Self::KP2_FIELD.read(self.0))
    }

    pub(crate) fn ki(self) -> IntegralCurrentGain {
        generated_field(Self::KI_FIELD.read(self.0))
    }

    pub(crate) fn kp_brake(self) -> PidScale {
        generated_field(Self::KP_BRAKE_FIELD.read(self.0))
    }

    pub(crate) fn kp2_brake(self) -> PidScale {
        generated_field(Self::KP2_BRAKE_FIELD.read(self.0))
    }

    pub(crate) fn ki_limit(self) -> MotorCurrentLimit {
        MotorCurrentLimit::new(generated_field(Self::KI_LIMIT_FIELD.read(self.0)).current())
    }

    pub(crate) fn booster_angle(self) -> AngleDegrees {
        generated_field(Self::BOOSTER_ANGLE_FIELD.read(self.0))
    }

    pub(crate) fn booster_ramp(self) -> AngleDegrees {
        generated_field(Self::BOOSTER_RAMP_FIELD.read(self.0))
    }

    pub(crate) fn booster_current(self) -> MotorCurrent {
        generated_field(Self::BOOSTER_CURRENT_FIELD.read(self.0))
    }

    pub(crate) fn brake_booster_angle(self) -> AngleDegrees {
        generated_field(Self::BRAKE_BOOSTER_ANGLE_FIELD.read(self.0))
    }

    pub(crate) fn brake_booster_ramp(self) -> AngleDegrees {
        generated_field(Self::BRAKE_BOOSTER_RAMP_FIELD.read(self.0))
    }

    pub(crate) fn brake_booster_current(self) -> MotorCurrent {
        generated_field(Self::BRAKE_BOOSTER_CURRENT_FIELD.read(self.0))
    }

    pub(crate) fn torque_tilt_start_current(self) -> MotorCurrent {
        generated_field(Self::TORQUE_TILT_START_CURRENT_FIELD.read(self.0))
    }

    pub(crate) fn torque_tilt_angle_limit(self) -> AngleDegrees {
        generated_field(Self::TORQUE_TILT_ANGLE_LIMIT_FIELD.read(self.0))
    }

    pub(crate) fn torque_tilt_on_speed(self) -> AngularVelocity {
        generated_field(Self::TORQUE_TILT_ON_SPEED_FIELD.read(self.0))
    }

    pub(crate) fn torque_tilt_off_speed(self) -> AngularVelocity {
        generated_field(Self::TORQUE_TILT_OFF_SPEED_FIELD.read(self.0))
    }

    pub(crate) fn torque_tilt_strength(self) -> PidScale {
        generated_field(Self::TORQUE_TILT_STRENGTH_FIELD.read(self.0))
    }

    pub(crate) fn torque_tilt_regen_strength(self) -> PidScale {
        generated_field(Self::TORQUE_TILT_REGEN_STRENGTH_FIELD.read(self.0))
    }

    pub(crate) fn turn_tilt_strength(self) -> PidScale {
        generated_field(Self::TURN_TILT_STRENGTH_FIELD.read(self.0))
    }

    pub(crate) fn turn_tilt_angle_limit(self) -> AngleDegrees {
        generated_field(Self::TURN_TILT_ANGLE_LIMIT_FIELD.read(self.0))
    }

    pub(crate) fn turn_tilt_start_angle(self) -> AngleDegrees {
        generated_field(Self::TURN_TILT_START_ANGLE_FIELD.read(self.0))
    }

    pub(crate) fn turn_tilt_start_erpm(self) -> ElectricalSpeed {
        generated_field(Self::TURN_TILT_START_ERPM_FIELD.read(self.0))
    }

    pub(crate) fn turn_tilt_speed(self) -> AngularVelocity {
        generated_field(Self::TURN_TILT_SPEED_FIELD.read(self.0))
    }

    pub(crate) fn turn_tilt_erpm_boost(self) -> u16 {
        u16::from_be_bytes([self.0.as_bytes()[140], self.0.as_bytes()[141]])
    }

    pub(crate) fn turn_tilt_erpm_boost_end(self) -> Rpm {
        Rpm::from_revolutions_per_minute(f32::from(u16::from_be_bytes([
            self.0.as_bytes()[142],
            self.0.as_bytes()[143],
        ])))
    }

    pub(crate) fn turn_tilt_yaw_aggregate(self) -> AngleDegrees {
        AngleDegrees::from_degrees(f32::from(self.0.as_bytes()[144]))
    }

    pub(crate) fn atr_strength_up(self) -> PidScale {
        generated_field(Self::ATR_STRENGTH_UP_FIELD.read(self.0))
    }

    pub(crate) fn atr_strength_down(self) -> PidScale {
        generated_field(Self::ATR_STRENGTH_DOWN_FIELD.read(self.0))
    }

    pub(crate) fn atr_threshold_up(self) -> AngleDegrees {
        generated_field(Self::ATR_THRESHOLD_UP_FIELD.read(self.0))
    }

    pub(crate) fn atr_threshold_down(self) -> AngleDegrees {
        generated_field(Self::ATR_THRESHOLD_DOWN_FIELD.read(self.0))
    }

    pub(crate) fn atr_speed_boost(self) -> PidScale {
        generated_field(Self::ATR_SPEED_BOOST_FIELD.read(self.0))
    }

    pub(crate) fn atr_angle_limit(self) -> AngleDegrees {
        generated_field(Self::ATR_ANGLE_LIMIT_FIELD.read(self.0))
    }

    pub(crate) fn atr_on_speed(self) -> AngularVelocity {
        generated_field(Self::ATR_ON_SPEED_FIELD.read(self.0))
    }

    pub(crate) fn atr_off_speed(self) -> AngularVelocity {
        generated_field(Self::ATR_OFF_SPEED_FIELD.read(self.0))
    }

    pub(crate) fn atr_response_boost(self) -> PidScale {
        generated_field(Self::ATR_RESPONSE_BOOST_FIELD.read(self.0))
    }

    pub(crate) fn atr_transition_boost(self) -> PidScale {
        generated_field(Self::ATR_TRANSITION_BOOST_FIELD.read(self.0))
    }

    pub(crate) fn atr_amps_accel_ratio(self) -> PidScale {
        generated_field(Self::ATR_AMPS_ACCEL_RATIO_FIELD.read(self.0))
    }

    pub(crate) fn atr_amps_decel_ratio(self) -> PidScale {
        generated_field(Self::ATR_AMPS_DECEL_RATIO_FIELD.read(self.0))
    }

    pub(crate) fn brake_tilt_strength(self) -> PidScale {
        generated_field(Self::BRAKE_TILT_STRENGTH_FIELD.read(self.0))
    }

    pub(crate) fn brake_tilt_lingering(self) -> PidScale {
        generated_field(Self::BRAKE_TILT_LINGERING_FIELD.read(self.0))
    }
}

#[derive(Debug, Clone, Copy, PartialEq)]
#[repr(transparent)]
pub(crate) struct RefloatRemoteThrottleConfig<'a>(&'a RefloatConfigImage);

impl RefloatRemoteThrottleConfig<'_> {
    // Upstream serializes remote throttle fields immediately before startup
    // tolerances at `third_party/refloat/src/conf/settings.xml:3962-3965`.
    const INVERT_THROTTLE_FIELD: CustomConfigFlagField = vescpkg_rs::generated_custom_config_field!(CustomConfigFlagField, len: REFLOAT_CONFIG_LEN, offset: 84);
    const CURRENT_MAX_FIELD: CustomConfigMotorCurrentField = vescpkg_rs::generated_custom_config_field!(CustomConfigMotorCurrentField, len: REFLOAT_CONFIG_LEN, offset: 87, scale: 10.0);
    const GRACE_PERIOD_FIELD: CustomConfigSecondsField = vescpkg_rs::generated_custom_config_field!(CustomConfigSecondsField, len: REFLOAT_CONFIG_LEN, offset: 89, scale: 10.0);

    pub(crate) fn current_max(self) -> MotorCurrent {
        generated_field(Self::CURRENT_MAX_FIELD.read(self.0))
    }

    pub(crate) fn grace_period(self) -> VescSeconds {
        generated_field(Self::GRACE_PERIOD_FIELD.read(self.0))
    }

    pub(crate) fn invert_throttle(self) -> bool {
        self.0.flag(Self::INVERT_THROTTLE_FIELD)
    }
}

// Upstream HANDTEST temporarily disables tune modifiers at
// `third_party/refloat/src/main.c:1431-1444`; these offsets follow the
// generated serialized field order in `third_party/refloat/src/conf/settings.xml:3943-3961`.
const TILTBACK_CONSTANT_FIELD: CustomConfigResetField = vescpkg_rs::generated_custom_config_field!(CustomConfigResetField, len: REFLOAT_CONFIG_LEN, offset: 67);
const TILTBACK_VARIABLE_FIELD: CustomConfigResetField = vescpkg_rs::generated_custom_config_field!(CustomConfigResetField, len: REFLOAT_CONFIG_LEN, offset: 71);
const TORQUE_TILT_STRENGTH_FIELD: CustomConfigResetField = vescpkg_rs::generated_custom_config_field!(CustomConfigResetField, len: REFLOAT_CONFIG_LEN, offset: 126);
const TORQUE_TILT_REGEN_STRENGTH_FIELD: CustomConfigResetField = vescpkg_rs::generated_custom_config_field!(CustomConfigResetField, len: REFLOAT_CONFIG_LEN, offset: 128);
const TURN_TILT_STRENGTH_FIELD: CustomConfigResetField = vescpkg_rs::generated_custom_config_field!(CustomConfigResetField, len: REFLOAT_CONFIG_LEN, offset: 130);
const ATR_STRENGTH_UP_FIELD: CustomConfigResetField = vescpkg_rs::generated_custom_config_field!(CustomConfigResetField, len: REFLOAT_CONFIG_LEN, offset: 145);
const ATR_STRENGTH_DOWN_FIELD: CustomConfigResetField = vescpkg_rs::generated_custom_config_field!(CustomConfigResetField, len: REFLOAT_CONFIG_LEN, offset: 147);
