//! Float Out Boy generated custom-config bytes and field layout.
//!
//! This module keeps generated byte layout private behind typed Float Out Boy views.

use crate::balance::LoopConfig;
use crate::bms::{FloatOutBoyBmsTemperature, FloatOutBoyBmsThresholds};
#[cfg(any(test, target_arch = "arm"))]
use crate::domain::FloatOutBoyFootpadAdcMapping;
use crate::{
    lcm::{FloatOutBoyHardwareLedsConfig, FloatOutBoyLedMode},
    leds::{
        FloatOutBoyLedAnimationMode, FloatOutBoyLedBarConfig, FloatOutBoyLedColor,
        FloatOutBoyLedColorOrder, FloatOutBoyLedPin, FloatOutBoyLedPinConfig,
        FloatOutBoyLedStripConfig, FloatOutBoyLedStripOrder, FloatOutBoyLedTransition,
        FloatOutBoyLedsConfig, FloatOutBoyStatusBarConfig,
    },
};
use vescpkg_rs::CustomConfigResetField;
use vescpkg_rs::CustomConfigVoltageField;
use vescpkg_rs::prelude::{
    AngleCurrentGain, AngleDegrees, AngularVelocity, ElectricalSpeed, IntegralCurrentGain,
    MahonyPitchGain, MahonyRollGain, MotorCurrent, MotorCurrentLimit, PidScale, RateCurrentGain,
    Ratio, Rpm, SampleRate, Speed, VescSeconds, Voltage,
};
use vescpkg_rs::prelude::{AudioFrequency, AudioVoltage};
use vescpkg_rs::{
    CustomConfigAngleCurrentGainField, CustomConfigAngleField, CustomConfigAngularVelocityField,
    CustomConfigCursor, CustomConfigDurationField, CustomConfigEditor,
    CustomConfigElectricalSpeedField, CustomConfigEnumField, CustomConfigFlagField,
    CustomConfigFrequencyField, CustomConfigImage, CustomConfigIntegralCurrentGainField,
    CustomConfigMahonyPitchGainField, CustomConfigMahonyRollGainField,
    CustomConfigMotorCurrentField, CustomConfigPidScaleField, CustomConfigRateCurrentGainField,
    CustomConfigRatioField, CustomConfigScaledVoltageField, CustomConfigSecondsField,
    CustomConfigWireByteField, WireByte,
};

mod flywheel;
mod handtest_safety;

pub(crate) use flywheel::FloatOutBoyFlywheelConfig;

// Pinned Refloat cutoff generated custom-config XML blob. The checked source is
// `conf/settings.xml`; upstream generates the equivalent data from that file via
// `third_party/float-out-boy/src/Makefile:28-31` and exposes `data_float_out_boy_config_` through `get_cfg_xml` at
// `third_party/float-out-boy/src/main.c:2388-2396`.
vescpkg_rs::firmware_section_static!(
    ".text.float_out_boy_config_xml",
    pub(crate) static FLOAT_OUT_BOY_CONFIG_XML: [u8; 27_514] = *include_bytes!("conf/float_out_boy_config.dat")
);

// Pinned Refloat cutoff generated serialized default custom config. Upstream
// `get_cfg(..., is_default=true)` allocates `FloatOutBoyConfig`, fills defaults,
// serializes it, then frees it at `third_party/float-out-boy/src/main.c:2335-2356`.
// `third_party/float-out-boy/src/Makefile:12-13` declares the generated
// `conf/confparser.*` files, and `third_party/float-out-boy/src/Makefile:28-29`
// regenerates them from `third_party/float-out-boy/src/conf/settings.xml`.
vescpkg_rs::firmware_section_static!(
    ".text.float_out_boy_default_config",
    pub(crate) static FLOAT_OUT_BOY_DEFAULT_CONFIG: [u8; 282] = *include_bytes!("conf/default_config.dat")
);
// Upstream generated `conf/confparser.h` derives signature `421162011`
// (`0x191a6c1b`) and serialized length `282` from
// `third_party/float-out-boy/src/conf/settings.xml`; the generator is wired in
// `third_party/float-out-boy/src/Makefile:12-29`.
pub(crate) const FLOAT_OUT_BOY_CONFIG_SIGNATURE_BYTES: [u8; 4] = [0x19, 0x1a, 0x6c, 0x1b];
pub(crate) const FLOAT_OUT_BOY_CONFIG_LEN: usize = FLOAT_OUT_BOY_DEFAULT_CONFIG.len();
pub(crate) const FLOAT_OUT_BOY_MAIN_THREAD_SAMPLE_RATE: SampleRate = SampleRate::from_hertz(500.0);
pub(crate) const FLOAT_OUT_BOY_DEFAULT_LIGHTS_OFF_WHEN_LIFTED: bool =
    FLOAT_OUT_BOY_DEFAULT_CONFIG[184] != 0;
pub(crate) const FLOAT_OUT_BOY_DEFAULT_HARDWARE_LED_MODE: u8 = FLOAT_OUT_BOY_DEFAULT_CONFIG[232];
pub(crate) const FLOAT_OUT_BOY_DEFAULT_BEEPER_ENABLED: bool =
    FLOAT_OUT_BOY_DEFAULT_CONFIG[248] != 0;

fn is_tune_default_byte(index: usize) -> bool {
    matches!(
        index,
        4..=17 | 24..=27 | 87..=94 | 97..=98 | 108..=117 | 119..=134 | 143..=179 | 248
    )
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub(crate) struct FloatOutBoySetpointFilterConfig {
    time_constant: VescSeconds,
    on_speed_time_constant: VescSeconds,
    off_speed_time_constant: VescSeconds,
    on_speed_limit: AngularVelocity,
    off_speed_limit: AngularVelocity,
}

impl FloatOutBoySetpointFilterConfig {
    const fn new(
        time_constant: VescSeconds,
        on_speed_time_constant: VescSeconds,
        off_speed_time_constant: VescSeconds,
        on_speed_limit: AngularVelocity,
        off_speed_limit: AngularVelocity,
    ) -> Self {
        Self {
            time_constant,
            on_speed_time_constant,
            off_speed_time_constant,
            on_speed_limit,
            off_speed_limit,
        }
    }

    pub(crate) const fn time_constant(self) -> VescSeconds {
        self.time_constant
    }
    pub(crate) const fn on_speed_time_constant(self) -> VescSeconds {
        self.on_speed_time_constant
    }
    pub(crate) const fn off_speed_time_constant(self) -> VescSeconds {
        self.off_speed_time_constant
    }
    pub(crate) const fn on_speed_limit(self) -> AngularVelocity {
        self.on_speed_limit
    }
    pub(crate) const fn off_speed_limit(self) -> AngularVelocity {
        self.off_speed_limit
    }
}

#[cfg(test)]
fn generated_field<T: Default>(value: Option<T>) -> T {
    // Generated offsets should always fit the fixed-size configuration image.
    // If the generated layout and image ever disagree, use the field type's
    // inert value instead of panicking inside the embedded control loop.
    value.unwrap_or_default()
}

macro_rules! config_views {
    ($( $getter:ident => $view:ident; )+) => {
        $(
            pub(crate) const fn $getter(&self) -> $view<'_> {
                $view(self)
            }
        )+
    };
}

#[cfg(test)]
macro_rules! generated_config_setters {
    ($(
        $(#[$attribute:meta])*
        $setter:ident($argument:ident: $value_type:ty) => $config:ident::$field:ident;
    )*) => {$(
        $(#[$attribute])*
        pub(crate) fn $setter(&mut self, $argument: $value_type) -> bool {
            $config::$field.write(self, $argument).is_some()
        }
    )*};
}

#[cfg(test)]
mod generated_field_tests;

#[cfg(test)]
mod led_config_tests;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(transparent)]
pub(crate) struct FloatOutBoyConfigImage(CustomConfigImage<FLOAT_OUT_BOY_CONFIG_LEN>);

impl Default for FloatOutBoyConfigImage {
    fn default() -> Self {
        Self::defaults()
    }
}

impl core::ops::Deref for FloatOutBoyConfigImage {
    type Target = CustomConfigImage<FLOAT_OUT_BOY_CONFIG_LEN>;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl FloatOutBoyConfigImage {
    vescpkg_rs::generated_custom_config_image_fields! {
        len: FLOAT_OUT_BOY_CONFIG_LEN;
        visibility: pub(crate),
        ATR_FILTER_FIELD: CustomConfigFrequencyField => motor_current_filter_frequency -> vescpkg_rs::Frequency, offset: 170, scale: 100.0;
        DUTY_PUSHBACK_ANGLE_FIELD: CustomConfigAngleField => duty_pushback_angle -> AngleDegrees, offset: 64, scale: 100.0;
        DUTY_PUSHBACK_SPEED_FIELD: CustomConfigAngularVelocityField => duty_pushback_speed -> AngularVelocity, offset: 66, scale: 100.0;
        DUTY_PUSHBACK_THRESHOLD_FIELD: CustomConfigRatioField => duty_pushback_threshold -> Ratio, offset: 68, scale: 1000.0;
        DUTY_BEEP_ENABLED_FIELD: CustomConfigFlagField => duty_beep_enabled -> bool, offset: 70;
        FOOT_BEEP_ENABLED_FIELD: CustomConfigFlagField => foot_beep_enabled -> bool, offset: 48;
        TILTBACK_RETURN_SPEED_FIELD: CustomConfigAngularVelocityField => tiltback_return_speed -> AngularVelocity, offset: 84, scale: 100.0;
        PERSISTENT_FATAL_ERROR_FIELD: CustomConfigFlagField => persistent_fatal_error -> bool, offset: 86;
        TILTBACK_CONSTANT_ANGLE_FIELD: CustomConfigAngleField => tiltback_constant -> AngleDegrees, offset: 87, scale: 1000.0;
        TILTBACK_CONSTANT_ERPM_FIELD: CustomConfigElectricalSpeedField => tiltback_constant_erpm -> ElectricalSpeed, offset: 89;
        TILTBACK_VARIABLE_RATE_FIELD: CustomConfigPidScaleField => tiltback_variable -> PidScale, offset: 91, scale: 1000.0;
        TILTBACK_VARIABLE_MAX_FIELD: CustomConfigAngleField => tiltback_variable_max -> AngleDegrees, offset: 93, scale: 100.0;
        TILTBACK_VARIABLE_ERPM_FIELD: CustomConfigElectricalSpeedField => tiltback_variable_erpm -> ElectricalSpeed, offset: 95;
        NOSE_ANGLING_SPEED_FIELD: CustomConfigAngularVelocityField => nose_angling_speed -> AngularVelocity, offset: 97, scale: 100.0;
        INPUT_TILT_ANGLE_LIMIT_FIELD: CustomConfigAngleField => input_tilt_angle_limit -> AngleDegrees, offset: 100, scale: 100.0;
        HIGH_VOLTAGE_PUSHBACK_ANGLE_FIELD: CustomConfigAngleField => high_voltage_pushback_angle -> AngleDegrees, offset: 71, scale: 100.0;
        HIGH_VOLTAGE_THRESHOLD_FIELD: CustomConfigScaledVoltageField => high_voltage_threshold -> Voltage, offset: 75, scale: 100.0;
        LOW_VOLTAGE_PUSHBACK_ANGLE_FIELD: CustomConfigAngleField => low_voltage_pushback_angle -> AngleDegrees, offset: 77, scale: 100.0;
        LOW_VOLTAGE_THRESHOLD_FIELD: CustomConfigScaledVoltageField => low_voltage_threshold -> Voltage, offset: 81, scale: 100.0;
        BEEPER_ENABLED_FIELD: CustomConfigFlagField => beeper_enabled -> bool, offset: 248;
        LEDS_ON_FIELD: CustomConfigFlagField => leds_enabled -> bool, offset: 180;
        LEDS_HEADLIGHTS_ON_FIELD: CustomConfigFlagField => headlights_enabled -> bool, offset: 181;
        #[cfg(test)]
        LEDS_LIGHTS_OFF_WHEN_LIFTED_FIELD: CustomConfigFlagField => lights_off_when_lifted -> bool, offset: 184;
        INPUT_TILT_REMOTE_TYPE_FIELD: CustomConfigWireByteField => input_tilt_remote_type -> u8, offset: 99, map: WireByte::as_u8;
        INPUT_TILT_INVERT_FIELD: CustomConfigFlagField => input_tilt_inverted -> bool, offset: 102;
        INPUT_TILT_DEADBAND_FIELD: CustomConfigRatioField => input_tilt_deadband -> Ratio, offset: 103, scale: 10000.0;
        #[cfg(any(test, target_arch = "arm"))]
        FOOTPAD_ADC_SWAP_FIELD: CustomConfigFlagField => footpad_adc_swapped -> bool, offset: 247;
        SPEED_PUSHBACK_THRESHOLD_FIELD: CustomConfigWireByteField => speed_pushback_threshold -> Speed, offset: 83, map: |value: WireByte| value.scaled(1.0, 0.0, Speed::from_kilometers_per_hour);
        HARDWARE_LED_MODE_FIELD: CustomConfigEnumField<FloatOutBoyHardwareLedMode> => hardware_led_mode_id -> u8, offset: 232, map: WireByte::as_u8;
    }
    // The cutoff schema serializes `is_beeper_enabled` after the 15-byte
    // hardware LED block beginning at offset 232 and immediately before
    // `disabled` at offset 249.

    // Generated `hardware.leds.mode` follows the 52-byte `leds` block beginning
    // at offset 180 in the pinned cutoff's generated `confparser.c`.
    // These fields immediately follow `braketilt_lingering` in the generated
    // `SerOrder` at `third_party/float-out-boy/src/conf/settings.xml:4134-4140`.
    // The generated default image confirms the bytes at 180, 181, and 184 as
    // the default-on LEDs/headlights and lifted-lights flags.
    pub(crate) const fn defaults() -> Self {
        Self(CustomConfigImage::new(FLOAT_OUT_BOY_DEFAULT_CONFIG))
    }

    pub(crate) fn from_serialized(bytes: &[u8]) -> Option<Self> {
        // C map: `read_cfg_from_eeprom` and `set_cfg` both accept only
        // successfully deserialized Float Out Boy config images at
        // `third_party/float-out-boy/src/main.c:1178-1185` and
        // `third_party/float-out-boy/src/main.c:2368-2386`.
        let bytes = <&[u8; FLOAT_OUT_BOY_CONFIG_LEN]>::try_from(bytes).ok()?;
        if !bytes.starts_with(&FLOAT_OUT_BOY_CONFIG_SIGNATURE_BYTES) {
            return None;
        }
        Self::has_valid_semantics(bytes).then(|| Self(CustomConfigImage::new(*bytes)))
    }

    fn has_valid_semantics(bytes: &[u8; FLOAT_OUT_BOY_CONFIG_LEN]) -> bool {
        let sample_rate = u16::from_be_bytes([bytes[18], bytes[19]]);
        (50..=4_000).contains(&sample_rate)
            && u16::from_be_bytes([bytes[103], bytes[104]]) < 10_000
            && bytes[99] <= 2
            && bytes[118] <= 2
            && validate_led_config(bytes).is_some()
            && u16::from_be_bytes([bytes[153], bytes[154]]) > 0
            && bytes[155] > 0
            && u16::from_be_bytes([bytes[250], bytes[251]]) > 0
            && u16::from_be_bytes([bytes[254], bytes[255]]) > 0
            && u16::from_be_bytes([bytes[258], bytes[259]]) > 0
    }

    pub(crate) const fn as_bytes(&self) -> &[u8; FLOAT_OUT_BOY_CONFIG_LEN] {
        self.0.as_bytes()
    }

    pub(crate) fn reset_tune_defaults(&mut self) {
        let mut bytes = *self.as_bytes();
        for (index, (byte, default)) in bytes
            .iter_mut()
            .zip(FLOAT_OUT_BOY_DEFAULT_CONFIG.iter())
            .enumerate()
        {
            if is_tune_default_byte(index) {
                *byte = *default;
            }
        }
        self.0 = CustomConfigImage::new(bytes);
    }

    pub(crate) fn led_configs(
        &self,
    ) -> Option<(FloatOutBoyHardwareLedsConfig, FloatOutBoyLedsConfig)> {
        decode_led_config(self.as_bytes())
    }

    config_views! {
        balance => FloatOutBoyBalanceConfig;
        filter => FloatOutBoyFilterConfig;
        faults => FloatOutBoyFaultConfig;
        startup => FloatOutBoyStartupConfig;
        motor_control => FloatOutBoyMotorControlConfig;
        metadata => FloatOutBoyMetadataConfig;
    }

    pub(crate) const fn remote(&self) -> FloatOutBoyRemoteConfig<'_> {
        FloatOutBoyRemoteConfig(self)
    }

    config_views! {
        bms => FloatOutBoyBmsConfig;
        haptic => FloatOutBoyHapticConfig;
    }

    #[cfg(test)]
    pub(crate) fn set_haptic_current_threshold(&mut self, threshold: Ratio) -> bool {
        let mut editor = self.editor();
        FloatOutBoyHapticConfig::CURRENT_THRESHOLD_FIELD
            .write(&mut editor, threshold)
            .is_some()
    }

    pub(crate) fn balance_loop_config(&self) -> LoopConfig {
        // C map: `configure(d)` consumes these generated `float_conf` fields to
        // drive the control loop and timing at `third_party/float-out-boy/src/main.c:161-199`;
        // the serialized field order is pinned in `third_party/float-out-boy/src/conf/settings.xml:3917-3981`.
        let balance = self.balance();
        LoopConfig {
            kp: balance.kp(),
            kp2: balance.kp2(),
            ki: balance.ki(),
            kp_brake: balance.kp_brake(),
            kp2_brake: balance.kp2_brake(),
            ki_limit: balance.ki_limit(),
            booster_angle: balance.booster_angle(),
            booster_ramp: balance.booster_ramp(),
            booster_current: balance.booster_current(),
            brkbooster_angle: balance.brake_booster_angle(),
            brkbooster_ramp: balance.brake_booster_ramp(),
            brkbooster_current: balance.brake_booster_current(),
            hertz: FLOAT_OUT_BOY_MAIN_THREAD_SAMPLE_RATE,
        }
    }

    pub(crate) fn editor(&mut self) -> FloatOutBoyConfigEditor<'_> {
        FloatOutBoyConfigEditor(self.0.editor())
    }

    #[cfg(any(test, target_arch = "arm"))]
    pub(crate) fn footpad_adc_mapping(&self) -> FloatOutBoyFootpadAdcMapping {
        FloatOutBoyFootpadAdcMapping::from_swapped(self.footpad_adc_swapped())
    }
}

vescpkg_rs::generated_custom_config_view! {
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub(crate) struct FloatOutBoyHapticConfig<'a>(&'a FloatOutBoyConfigImage);
    len: FLOAT_OUT_BOY_CONFIG_LEN;
    fields {
        DUTY_FREQUENCY_FIELD: CustomConfigFrequencyField => duty_frequency -> AudioFrequency, offset: 250, scale: 1.0, map: AudioFrequency::new;
        DUTY_STRENGTH_FIELD: CustomConfigScaledVoltageField => duty_strength -> AudioVoltage, offset: 252, scale: 10.0, map: AudioVoltage::new;
        ERROR_FREQUENCY_FIELD: CustomConfigFrequencyField => error_frequency -> AudioFrequency, offset: 254, scale: 1.0, map: AudioFrequency::new;
        ERROR_STRENGTH_FIELD: CustomConfigScaledVoltageField => error_strength -> AudioVoltage, offset: 256, scale: 10.0, map: AudioVoltage::new;
        VIBRATE_FREQUENCY_FIELD: CustomConfigFrequencyField => vibrate_frequency -> AudioFrequency, offset: 258, scale: 1.0, map: AudioFrequency::new;
        VIBRATE_STRENGTH_FIELD: CustomConfigMotorCurrentField => vibrate_strength -> MotorCurrent, offset: 260, scale: 10.0;
        DUTY_SOLID_OFFSET_FIELD: CustomConfigRatioField => duty_solid_offset -> Ratio, offset: 262, scale: 10000.0;
        CURRENT_THRESHOLD_FIELD: CustomConfigRatioField => current_threshold -> Ratio, offset: 264, scale: 10000.0;
        MIN_STRENGTH_FIELD: CustomConfigRatioField => min_strength -> Ratio, offset: 266, scale: 10000.0;
        STRENGTH_CURVATURE_FIELD: CustomConfigRatioField => strength_curvature -> Ratio, offset: 269, scale: 1000.0;
        MAX_STRENGTH_SPEED_FIELD: CustomConfigWireByteField => max_strength_speed -> Speed, offset: 268, map: |value: WireByte| value.scaled(1.0, 0.0, Speed::from_kilometers_per_hour);
    }
}

type FloatOutBoyHardwareLedMode = WireByte;

fn decode_led_config(
    bytes: &[u8; FLOAT_OUT_BOY_CONFIG_LEN],
) -> Option<(FloatOutBoyHardwareLedsConfig, FloatOutBoyLedsConfig)> {
    let mut cursor = CustomConfigCursor::new(bytes, 180);
    let leds = FloatOutBoyLedsConfig {
        on: cursor.boolean()?,
        headlights_on: cursor.boolean()?,
        headlights_transition: cursor.enum_value()?,
        direction_transition: cursor.enum_value()?,
        lifted: crate::leds::FloatOutBoyLiftedLedsConfig {
            lights_off: cursor.boolean()?,
            status_on_front: cursor.boolean()?,
        },
        front: decode_led_bar(&mut cursor)?,
        rear: decode_led_bar(&mut cursor)?,
        headlights: decode_led_bar(&mut cursor)?,
        taillights: decode_led_bar(&mut cursor)?,
        status: FloatOutBoyStatusBarConfig {
            brightness_headlights_off: cursor.scaled_ratio(10_000.0)?,
            brightness_headlights_on: cursor.scaled_ratio(10_000.0)?,
            show_sensors_while_running: cursor.boolean()?,
            duty_threshold: cursor.scaled_ratio(10_000.0)?,
            red_bar_percentage: cursor.scaled_ratio(10_000.0)?,
            idle_timeout: cursor.be_u16()?,
        },
        status_idle: decode_led_bar(&mut cursor)?,
    };
    let hardware = FloatOutBoyHardwareLedsConfig {
        mode: cursor.enum_value()?,
        pin: cursor.enum_value()?,
        pin_config: cursor.enum_value()?,
        status: decode_led_strip(&mut cursor)?,
        front: decode_led_strip(&mut cursor)?,
        rear: decode_led_strip(&mut cursor)?,
    };

    (cursor.offset() == 247).then_some((hardware, leds))
}

fn validate_led_config(bytes: &[u8; FLOAT_OUT_BOY_CONFIG_LEN]) -> Option<()> {
    validate_led_enums::<FloatOutBoyLedTransition>(bytes, &[182, 183])?;
    validate_led_enums::<FloatOutBoyLedAnimationMode>(bytes, &[186, 193, 200, 207, 225])?;
    validate_led_enums::<FloatOutBoyLedColor>(
        bytes,
        &[189, 190, 196, 197, 203, 204, 210, 211, 228, 229],
    )?;
    validate_led_enums::<FloatOutBoyLedMode>(bytes, &[232])?;
    validate_led_enums::<FloatOutBoyLedPin>(bytes, &[233])?;
    validate_led_enums::<FloatOutBoyLedPinConfig>(bytes, &[234])?;
    validate_led_enums::<FloatOutBoyLedStripOrder>(bytes, &[235, 239, 243])?;
    validate_led_enums::<FloatOutBoyLedColorOrder>(bytes, &[237, 241, 245])?;
    for offset in [187, 194, 201, 208, 214, 216, 219, 221, 226] {
        let high = bytes.get(offset).copied()?;
        let low = bytes.get(offset.saturating_add(1)).copied()?;
        Ratio::from_ratio(f32::from(u16::from_be_bytes([high, low])) / 10_000.0).ok()?;
    }
    Some(())
}

fn validate_led_enums<T: TryFrom<u8>>(bytes: &[u8], offsets: &[usize]) -> Option<()> {
    for offset in offsets {
        T::try_from(bytes.get(*offset).copied()?).ok()?;
    }
    Some(())
}

fn decode_led_bar(cursor: &mut CustomConfigCursor<'_>) -> Option<FloatOutBoyLedBarConfig> {
    let animation_mode = cursor.enum_value()?;
    Some(FloatOutBoyLedBarConfig {
        brightness: cursor.scaled_ratio(10_000.0)?,
        primary_color: cursor.enum_value()?,
        secondary_color: cursor.enum_value()?,
        animation_mode,
        animation_speed: f32::from(cursor.be_u16()?) / 1_000.0,
    })
}

fn decode_led_strip(cursor: &mut CustomConfigCursor<'_>) -> Option<FloatOutBoyLedStripConfig> {
    Some(FloatOutBoyLedStripConfig {
        order: cursor.enum_value()?,
        count: cursor.byte()?,
        color_order: cursor.enum_value()?,
        reverse: cursor.boolean()?,
    })
}

pub(crate) struct FloatOutBoyConfigEditor<'a>(CustomConfigEditor<'a, FLOAT_OUT_BOY_CONFIG_LEN>);

impl<'a> core::ops::Deref for FloatOutBoyConfigEditor<'a> {
    type Target = CustomConfigEditor<'a, FLOAT_OUT_BOY_CONFIG_LEN>;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl core::ops::DerefMut for FloatOutBoyConfigEditor<'_> {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}

impl FloatOutBoyConfigEditor<'_> {
    pub(crate) fn clear_meta_is_default(&mut self) {
        // C map: `set_cfg` always clears `meta.is_default` after a write at
        // `third_party/float-out-boy/src/main.c:2375-2377`.
        let _ = self.set(FloatOutBoyMetadataConfig::IS_DEFAULT_FIELD, false);
    }

    pub(crate) fn set_fault_pitch(&mut self, angle: AngleDegrees) -> bool {
        self.set(
            FloatOutBoyFaultConfig::PITCH_FIELD,
            WireByte::new(crate::wire::saturating_trunc_f32_to_u8(angle.as_degrees())),
        )
    }

    pub(crate) fn set_fault_roll(&mut self, angle: AngleDegrees) -> bool {
        self.set(
            FloatOutBoyFaultConfig::ROLL_FIELD,
            WireByte::new(crate::wire::saturating_trunc_f32_to_u8(angle.as_degrees())),
        )
    }

    #[cfg(test)]
    pub(crate) fn set_meta_is_default(&mut self, is_default: bool) -> bool {
        self.set(FloatOutBoyMetadataConfig::IS_DEFAULT_FIELD, is_default)
    }

    pub(crate) fn keep_enabled_while_running(&mut self) {
        // C map: `set_cfg` refuses to persist package disablement while
        // RUNNING at `third_party/float-out-boy/src/main.c:2370-2373`.
        let _ = self.set(FloatOutBoyMetadataConfig::DISABLED_FIELD, false);
    }
}

#[cfg(test)]
impl FloatOutBoyConfigEditor<'_> {
    pub(crate) fn set_ki_limit(&mut self, current: MotorCurrent) -> bool {
        if !current.is_finite() || current.is_negative() {
            return false;
        }
        self.set(FloatOutBoyBalanceConfig::KI_LIMIT_FIELD, current)
    }

    generated_config_setters! {
        set_disabled(disabled: bool) => FloatOutBoyMetadataConfig::DISABLED_FIELD;
        set_beeper_enabled(enabled: bool) => FloatOutBoyConfigImage::BEEPER_ENABLED_FIELD;
    }

    generated_config_setters! { set_startup_pitch_tolerance(angle: AngleDegrees) => FloatOutBoyStartupConfig::PITCH_TOLERANCE_FIELD; }

    generated_config_setters! { set_startup_roll_tolerance(angle: AngleDegrees) => FloatOutBoyStartupConfig::ROLL_TOLERANCE_FIELD; }

    generated_config_setters! { set_startup_speed(speed: AngularVelocity) => FloatOutBoyStartupConfig::SPEED_FIELD; }

    generated_config_setters! {
        set_pushstart_enabled(enabled: bool) => FloatOutBoyStartupConfig::PUSHSTART_FIELD;
        set_simplestart_enabled(enabled: bool) => FloatOutBoyStartupConfig::SIMPLESTART_FIELD;
        set_reversestop_enabled(enabled: bool) => FloatOutBoyFaultConfig::REVERSESTOP_FIELD;
        set_darkride_enabled(enabled: bool) => FloatOutBoyFaultConfig::DARKRIDE_FIELD;
        set_dual_switch(enabled: bool) => FloatOutBoyFaultConfig::DUAL_SWITCH_FIELD;
    }

    #[cfg(test)]
    generated_config_setters! { set_remote_grace_period(duration: VescSeconds) => FloatOutBoyRemoteConfig::GRACE_PERIOD_FIELD; }

    generated_config_setters! {
        set_kp(kp: AngleCurrentGain) => FloatOutBoyBalanceConfig::KP_FIELD;
        set_kp2(kp2: RateCurrentGain) => FloatOutBoyBalanceConfig::KP2_FIELD;
        set_ki(ki: IntegralCurrentGain) => FloatOutBoyBalanceConfig::KI_FIELD;
        set_kp_brake(scale: PidScale) => FloatOutBoyBalanceConfig::KP_BRAKE_FIELD;
    }

    generated_config_setters! { set_mahony_kp(gain: MahonyPitchGain) => FloatOutBoyFilterConfig::MAHONY_KP_FIELD; }

    #[cfg(test)]
    generated_config_setters! { set_speed_pushback_threshold(speed: vescpkg_rs::WireByte) => FloatOutBoyConfigImage::SPEED_PUSHBACK_THRESHOLD_FIELD; }

    generated_config_setters! { set_dirty_landings_enabled(enabled: bool) => FloatOutBoyStartupConfig::DIRTY_LANDINGS_FIELD; }

    generated_config_setters! { set_startup_click_current(current: vescpkg_rs::WireByte) => FloatOutBoyStartupConfig::CLICK_CURRENT_FIELD; }

    generated_config_setters! { set_tiltback_constant(angle: AngleDegrees) => FloatOutBoyConfigImage::TILTBACK_CONSTANT_ANGLE_FIELD; }

    generated_config_setters! { set_tiltback_constant_erpm(erpm: ElectricalSpeed) => FloatOutBoyConfigImage::TILTBACK_CONSTANT_ERPM_FIELD; }

    generated_config_setters! { set_tiltback_variable(rate: PidScale) => FloatOutBoyConfigImage::TILTBACK_VARIABLE_RATE_FIELD; }

    generated_config_setters! { set_tiltback_variable_max(angle: AngleDegrees) => FloatOutBoyConfigImage::TILTBACK_VARIABLE_MAX_FIELD; }

    generated_config_setters! { set_tiltback_variable_erpm(erpm: ElectricalSpeed) => FloatOutBoyConfigImage::TILTBACK_VARIABLE_ERPM_FIELD; }

    generated_config_setters! { set_nose_angling_speed(speed: AngularVelocity) => FloatOutBoyConfigImage::NOSE_ANGLING_SPEED_FIELD; }

    generated_config_setters! { set_input_tilt_remote_type(remote: vescpkg_rs::WireByte) => FloatOutBoyConfigImage::INPUT_TILT_REMOTE_TYPE_FIELD; }

    generated_config_setters! { set_input_tilt_angle_limit(angle: AngleDegrees) => FloatOutBoyConfigImage::INPUT_TILT_ANGLE_LIMIT_FIELD; }

    #[cfg(test)]
    generated_config_setters! { set_input_tilt_inverted(inverted: bool) => FloatOutBoyConfigImage::INPUT_TILT_INVERT_FIELD; }

    #[cfg(test)]
    generated_config_setters! { set_input_tilt_deadband(deadband: Ratio) => FloatOutBoyConfigImage::INPUT_TILT_DEADBAND_FIELD; }

    generated_config_setters! {
        set_booster_angle(angle: AngleDegrees) => FloatOutBoyBalanceConfig::BOOSTER_ANGLE_FIELD;
        set_booster_ramp(angle: AngleDegrees) => FloatOutBoyBalanceConfig::BOOSTER_RAMP_FIELD;
        set_booster_current(current: MotorCurrent) => FloatOutBoyBalanceConfig::BOOSTER_CURRENT_FIELD;
        set_brake_booster_angle(angle: AngleDegrees) => FloatOutBoyBalanceConfig::BRAKE_BOOSTER_ANGLE_FIELD;
        set_brake_booster_ramp(angle: AngleDegrees) => FloatOutBoyBalanceConfig::BRAKE_BOOSTER_RAMP_FIELD;
        set_brake_booster_current(current: MotorCurrent) => FloatOutBoyBalanceConfig::BRAKE_BOOSTER_CURRENT_FIELD;
        set_torque_tilt_start_current(current: MotorCurrent) => FloatOutBoyBalanceConfig::TORQUE_TILT_START_CURRENT_FIELD;
        set_torque_tilt_angle_limit(angle: AngleDegrees) => FloatOutBoyBalanceConfig::TORQUE_TILT_ANGLE_LIMIT_FIELD;
        set_torque_tilt_on_speed_limit(speed: AngularVelocity) => FloatOutBoyBalanceConfig::TORQUE_TILT_FILTER_ON_SPEED_LIMIT_FIELD;
        set_torque_tilt_off_speed_limit(speed: AngularVelocity) => FloatOutBoyBalanceConfig::TORQUE_TILT_FILTER_OFF_SPEED_LIMIT_FIELD;
        set_torque_tilt_strength(strength: PidScale) => FloatOutBoyBalanceConfig::TORQUE_TILT_STRENGTH_FIELD;
        set_torque_tilt_regen_strength(strength: PidScale) => FloatOutBoyBalanceConfig::TORQUE_TILT_REGEN_STRENGTH_FIELD;
        set_turn_tilt_strength(strength: PidScale) => FloatOutBoyBalanceConfig::TURN_TILT_STRENGTH_FIELD;
        set_turn_tilt_angle_limit(angle: AngleDegrees) => FloatOutBoyBalanceConfig::TURN_TILT_ANGLE_LIMIT_FIELD;
        set_turn_tilt_start_erpm(speed: ElectricalSpeed) => FloatOutBoyBalanceConfig::TURN_TILT_START_ERPM_FIELD;
        set_atr_strength_up(strength: PidScale) => FloatOutBoyBalanceConfig::ATR_STRENGTH_UP_FIELD;
        set_atr_strength_down(strength: PidScale) => FloatOutBoyBalanceConfig::ATR_STRENGTH_DOWN_FIELD;
        set_atr_threshold_up(angle: AngleDegrees) => FloatOutBoyBalanceConfig::ATR_THRESHOLD_UP_FIELD;
        set_atr_threshold_down(angle: AngleDegrees) => FloatOutBoyBalanceConfig::ATR_THRESHOLD_DOWN_FIELD;
        set_atr_speed_boost(strength: PidScale) => FloatOutBoyBalanceConfig::ATR_SPEED_BOOST_FIELD;
        set_atr_angle_limit(angle: AngleDegrees) => FloatOutBoyBalanceConfig::ATR_ANGLE_LIMIT_FIELD;
        set_atr_on_speed_limit(speed: AngularVelocity) => FloatOutBoyBalanceConfig::ATR_FILTER_ON_SPEED_LIMIT_FIELD;
        set_atr_off_speed_limit(speed: AngularVelocity) => FloatOutBoyBalanceConfig::ATR_FILTER_OFF_SPEED_LIMIT_FIELD;
        set_atr_amps_accel_ratio(ratio: PidScale) => FloatOutBoyBalanceConfig::ATR_AMPS_ACCEL_RATIO_FIELD;
        set_atr_amps_decel_ratio(ratio: PidScale) => FloatOutBoyBalanceConfig::ATR_AMPS_DECEL_RATIO_FIELD;
        set_brake_tilt_strength(strength: PidScale) => FloatOutBoyBalanceConfig::BRAKE_TILT_STRENGTH_FIELD;
        set_brake_tilt_lingering(lingering: PidScale) => FloatOutBoyBalanceConfig::BRAKE_TILT_LINGERING_FIELD;
    }

    #[cfg(test)]
    generated_config_setters! { set_atr_filter_time_constant(duration: VescSeconds) => FloatOutBoyBalanceConfig::ATR_FILTER_TIME_CONSTANT_FIELD; }
}

// Upstream defines `disabled` in `third_party/float-out-boy/src/conf/settings.xml:3890-3902`;
// its `<ser>disabled</ser>` entry at `third_party/float-out-boy/src/conf/settings.xml:4064`.
// Upstream defines `meta.is_default` in `third_party/float-out-boy/src/conf/settings.xml:3903-3914`;
// its `<ser>meta.is_default</ser>` entry at `third_party/float-out-boy/src/conf/settings.xml:4083`.
vescpkg_rs::generated_custom_config_view! {
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub(crate) struct FloatOutBoyMetadataConfig<'a>(&'a FloatOutBoyConfigImage);
    len: FLOAT_OUT_BOY_CONFIG_LEN;
    fields {
        DISABLED_FIELD: CustomConfigFlagField => disabled -> bool, offset: 249;
    }
}

impl FloatOutBoyMetadataConfig<'_> {
    const IS_DEFAULT_FIELD: CustomConfigFlagField = vescpkg_rs::generated_custom_config_field!(
        CustomConfigFlagField,
        len: FLOAT_OUT_BOY_CONFIG_LEN,
        offset: 281
    );

    #[cfg(test)]
    pub(crate) fn is_default(self) -> bool {
        generated_field(Self::IS_DEFAULT_FIELD.read(self.0))
    }
}

// The pinned cutoff serialization places `bms.enabled` after the haptic fields
// and before the six BMS thresholds.
vescpkg_rs::generated_custom_config_view! {
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub(crate) struct FloatOutBoyBmsConfig<'a>(&'a FloatOutBoyConfigImage);
    len: FLOAT_OUT_BOY_CONFIG_LEN;
    fields {
        ENABLED_FIELD: CustomConfigFlagField => enabled -> bool, offset: 271;
        CELL_LOW_VOLTAGE_FIELD: CustomConfigScaledVoltageField => cell_low_voltage -> Voltage, offset: 272, scale: 1000.0;
        CELL_HIGH_VOLTAGE_FIELD: CustomConfigScaledVoltageField => cell_high_voltage -> Voltage, offset: 274, scale: 1000.0;
        CELL_BALANCE_VOLTAGE_FIELD: CustomConfigScaledVoltageField => cell_balance_voltage -> Voltage, offset: 276, scale: 1000.0;
    }
}

impl FloatOutBoyBmsConfig<'_> {
    const CELL_HIGH_TEMPERATURE_OFFSET: usize = 278;
    const CELL_LOW_TEMPERATURE_OFFSET: usize = 279;
    const BMS_HIGH_TEMPERATURE_OFFSET: usize = 280;

    pub(crate) fn thresholds(self) -> FloatOutBoyBmsThresholds {
        FloatOutBoyBmsThresholds::new(
            self.cell_low_voltage(),
            self.cell_high_voltage(),
            self.cell_balance_voltage(),
            FloatOutBoyBmsTemperature::from_config_byte(
                self.0.as_bytes()[Self::CELL_LOW_TEMPERATURE_OFFSET],
            ),
            FloatOutBoyBmsTemperature::from_config_byte(
                self.0.as_bytes()[Self::CELL_HIGH_TEMPERATURE_OFFSET],
            ),
            FloatOutBoyBmsTemperature::from_config_byte(
                self.0.as_bytes()[Self::BMS_HIGH_TEMPERATURE_OFFSET],
            ),
        )
    }
}

#[derive(Debug, Default, Clone, Copy, PartialEq, Eq)]
pub(crate) enum FloatOutBoyParkingBrakeMode {
    #[default]
    Always,
    Idle,
    Never,
    Unknown(u8),
}

impl From<u8> for FloatOutBoyParkingBrakeMode {
    fn from(value: u8) -> Self {
        match value {
            0 => Self::Always,
            1 => Self::Idle,
            2 => Self::Never,
            value => Self::Unknown(value),
        }
    }
}

// Upstream serializes default parking brake mode and brake current at
// `third_party/float-out-boy/src/conf/settings.xml:3973-3974`.
vescpkg_rs::generated_custom_config_view! {
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub(crate) struct FloatOutBoyMotorControlConfig<'a>(&'a FloatOutBoyConfigImage);
    len: FLOAT_OUT_BOY_CONFIG_LEN;
    fields {
        PARKING_BRAKE_MODE_FIELD: CustomConfigEnumField<FloatOutBoyParkingBrakeMode> => parking_brake_mode -> FloatOutBoyParkingBrakeMode, offset: 118;
        BRAKE_CURRENT_FIELD: CustomConfigMotorCurrentField => brake_current -> MotorCurrent, offset: 119, scale: 100.0;
    }
}

// Upstream serializes Mahony pitch/roll KP after `ki` at
// `third_party/float-out-boy/src/conf/settings.xml:3916-3921`; both use scale 10000.
vescpkg_rs::generated_custom_config_view! {
    #[derive(Debug, Clone, Copy, PartialEq)]
    pub(crate) struct FloatOutBoyFilterConfig<'a>(&'a FloatOutBoyConfigImage);
    len: FLOAT_OUT_BOY_CONFIG_LEN;
    fields {
        MAHONY_KP_FIELD: CustomConfigMahonyPitchGainField => mahony_kp -> MahonyPitchGain, offset: 10, scale: 10000.0;
        MAHONY_KP_ROLL_FIELD: CustomConfigMahonyRollGainField => mahony_kp_roll -> MahonyRollGain, offset: 12, scale: 10000.0;
    }
}

// Upstream serializes fault angles, ADC thresholds, delays, ERPM gates,
// and feature flags at `third_party/float-out-boy/src/conf/settings.xml:3925-3939`.
vescpkg_rs::generated_custom_config_view! {
    #[derive(Debug, Clone, Copy, PartialEq)]
    pub(crate) struct FloatOutBoyFaultConfig<'a>(&'a FloatOutBoyConfigImage);
    len: FLOAT_OUT_BOY_CONFIG_LEN;
    fields {
        PITCH_FIELD: CustomConfigWireByteField => pitch_angle -> AngleDegrees, offset: 42, map: |value: WireByte| value.scaled(1.0, 0.0, AngleDegrees::from_degrees);
        ROLL_FIELD: CustomConfigWireByteField => roll_angle -> AngleDegrees, offset: 43, map: |value: WireByte| value.scaled(1.0, 0.0, AngleDegrees::from_degrees);
        ADC_HALF_ERPM_FIELD: CustomConfigElectricalSpeedField => adc_half_erpm -> ElectricalSpeed, offset: 57;
        ADC1_FIELD: CustomConfigVoltageField => adc1_voltage -> vescpkg_rs::Voltage, offset: 44;
        ADC2_FIELD: CustomConfigVoltageField => adc2_voltage -> vescpkg_rs::Voltage, offset: 46;
        DELAY_PITCH_FIELD: CustomConfigDurationField => pitch_delay -> VescSeconds, offset: 49;
        DELAY_ROLL_FIELD: CustomConfigDurationField => roll_delay -> VescSeconds, offset: 51;
        DELAY_SWITCH_HALF_FIELD: CustomConfigDurationField => switch_half_delay -> VescSeconds, offset: 53;
        DELAY_SWITCH_FULL_FIELD: CustomConfigDurationField => switch_full_delay -> VescSeconds, offset: 55;
        DUAL_SWITCH_FIELD: CustomConfigFlagField => dual_switch -> bool, offset: 59;
        MOVING_FAULT_DISABLED_FIELD: CustomConfigFlagField => moving_faults_disabled -> bool, offset: 60;
        QUICKSTOP_FIELD: CustomConfigFlagField => quickstop_enabled -> bool, offset: 61;
        DARKRIDE_FIELD: CustomConfigFlagField => darkride_enabled -> bool, offset: 62;
        REVERSESTOP_FIELD: CustomConfigFlagField => reversestop_enabled -> bool, offset: 63;
    }
}

// The pinned cutoff no longer serializes the legacy `hertz` field; startup
// fields begin at offset 108 in the new layout.
vescpkg_rs::generated_custom_config_view! {
    #[derive(Debug, Clone, Copy, PartialEq)]
    pub(crate) struct FloatOutBoyStartupConfig<'a>(&'a FloatOutBoyConfigImage);
    len: FLOAT_OUT_BOY_CONFIG_LEN;
    fields {
        PITCH_TOLERANCE_FIELD: CustomConfigAngleField => pitch_tolerance -> AngleDegrees, offset: 108, scale: 100.0;
        ROLL_TOLERANCE_FIELD: CustomConfigAngleField => roll_tolerance -> AngleDegrees, offset: 110, scale: 100.0;
        SPEED_FIELD: CustomConfigAngularVelocityField => startup_speed -> AngularVelocity, offset: 112, scale: 100.0;
        SIMPLESTART_FIELD: CustomConfigFlagField => simplestart_enabled -> bool, offset: 115;
        PUSHSTART_FIELD: CustomConfigFlagField => pushstart_enabled -> bool, offset: 116;
        CLICK_CURRENT_FIELD: CustomConfigWireByteField => click_current -> WireByte, offset: 114;
        DIRTY_LANDINGS_FIELD: CustomConfigFlagField => dirty_landings_enabled -> bool, offset: 117;
    }
}

impl FloatOutBoyStartupConfig<'_> {
    pub(crate) fn sample_rate(self) -> SampleRate {
        let _ = self;
        FLOAT_OUT_BOY_MAIN_THREAD_SAMPLE_RATE
    }

    pub(crate) fn loop_time_us(self) -> u32 {
        let _ = self;
        2_000
    }
}

// Upstream serializes balance tuning fields in
// `third_party/float-out-boy/src/conf/settings.xml:3916-3923,3975-3984`.
vescpkg_rs::generated_custom_config_view! {
    #[derive(Debug, Clone, Copy, PartialEq)]
    pub(crate) struct FloatOutBoyBalanceConfig<'a>(&'a FloatOutBoyConfigImage);
    len: FLOAT_OUT_BOY_CONFIG_LEN;
    fields {
        KP_FIELD: CustomConfigAngleCurrentGainField => kp -> AngleCurrentGain, offset: 4, scale: 10.0;
        KP2_FIELD: CustomConfigRateCurrentGainField => kp2 -> RateCurrentGain, offset: 6, scale: 100.0;
        KI_FIELD: CustomConfigIntegralCurrentGainField => ki -> IntegralCurrentGain, offset: 8, scale: 100_000.0;
        KP_BRAKE_FIELD: CustomConfigPidScaleField => kp_brake -> PidScale, offset: 14, scale: 100.0;
        KP2_BRAKE_FIELD: CustomConfigPidScaleField => kp2_brake -> PidScale, offset: 16, scale: 100.0;
        KI_LIMIT_FIELD: CustomConfigMotorCurrentField => ki_limit -> MotorCurrentLimit, offset: 121, scale: 10.0, map: |value: MotorCurrent| MotorCurrentLimit::new(value.current());
        BOOSTER_ANGLE_FIELD: CustomConfigAngleField => booster_angle -> AngleDegrees, offset: 123, scale: 100.0;
        BOOSTER_RAMP_FIELD: CustomConfigAngleField => booster_ramp -> AngleDegrees, offset: 125, scale: 100.0;
        BOOSTER_CURRENT_FIELD: CustomConfigMotorCurrentField => booster_current -> MotorCurrent, offset: 127, scale: 100.0;
        BRAKE_BOOSTER_ANGLE_FIELD: CustomConfigAngleField => brake_booster_angle -> AngleDegrees, offset: 129, scale: 100.0;
        BRAKE_BOOSTER_RAMP_FIELD: CustomConfigAngleField => brake_booster_ramp -> AngleDegrees, offset: 131, scale: 100.0;
        BRAKE_BOOSTER_CURRENT_FIELD: CustomConfigMotorCurrentField => brake_booster_current -> MotorCurrent, offset: 133, scale: 100.0;
        TORQUE_TILT_START_CURRENT_FIELD: CustomConfigMotorCurrentField => torque_tilt_start_current -> MotorCurrent, offset: 135, scale: 100.0;
        TORQUE_TILT_ANGLE_LIMIT_FIELD: CustomConfigAngleField => torque_tilt_angle_limit -> AngleDegrees, offset: 137, scale: 100.0;
        ATR_FILTER_TIME_CONSTANT_FIELD: CustomConfigSecondsField => atr_filter_time_constant -> VescSeconds, offset: 18, scale: 1000.0;
        ATR_FILTER_ON_SPEED_TIME_CONSTANT_FIELD: CustomConfigSecondsField => atr_filter_on_speed_time_constant -> VescSeconds, offset: 20, scale: 1000.0;
        ATR_FILTER_OFF_SPEED_TIME_CONSTANT_FIELD: CustomConfigSecondsField => atr_filter_off_speed_time_constant -> VescSeconds, offset: 22, scale: 1000.0;
        ATR_FILTER_ON_SPEED_LIMIT_FIELD: CustomConfigAngularVelocityField => atr_filter_on_speed_limit -> AngularVelocity, offset: 24, scale: 100.0;
        ATR_FILTER_OFF_SPEED_LIMIT_FIELD: CustomConfigAngularVelocityField => atr_filter_off_speed_limit -> AngularVelocity, offset: 26, scale: 100.0;
        TORQUE_TILT_FILTER_TIME_CONSTANT_FIELD: CustomConfigSecondsField => torque_tilt_filter_time_constant -> VescSeconds, offset: 28, scale: 1000.0;
        TORQUE_TILT_FILTER_ON_SPEED_TIME_CONSTANT_FIELD: CustomConfigSecondsField => torque_tilt_filter_on_speed_time_constant -> VescSeconds, offset: 30, scale: 1000.0;
        TORQUE_TILT_FILTER_OFF_SPEED_TIME_CONSTANT_FIELD: CustomConfigSecondsField => torque_tilt_filter_off_speed_time_constant -> VescSeconds, offset: 32, scale: 1000.0;
        TORQUE_TILT_FILTER_ON_SPEED_LIMIT_FIELD: CustomConfigAngularVelocityField => torque_tilt_filter_on_speed_limit -> AngularVelocity, offset: 34, scale: 100.0;
        TORQUE_TILT_FILTER_OFF_SPEED_LIMIT_FIELD: CustomConfigAngularVelocityField => torque_tilt_filter_off_speed_limit -> AngularVelocity, offset: 36, scale: 100.0;
        TURN_TILT_FILTER_TIME_CONSTANT_FIELD: CustomConfigSecondsField => turn_tilt_filter_time_constant -> VescSeconds, offset: 38, scale: 1000.0;
        REMOTE_FILTER_TIME_CONSTANT_FIELD: CustomConfigSecondsField => remote_filter_time_constant -> VescSeconds, offset: 40, scale: 1000.0;
        TORQUE_TILT_STRENGTH_FIELD: CustomConfigPidScaleField => torque_tilt_strength -> PidScale, offset: 139, scale: 1000.0;
        TORQUE_TILT_REGEN_STRENGTH_FIELD: CustomConfigPidScaleField => torque_tilt_regen_strength -> PidScale, offset: 141, scale: 1000.0;
        TURN_TILT_STRENGTH_FIELD: CustomConfigPidScaleField => turn_tilt_strength -> PidScale, offset: 143, scale: 100.0;
        TURN_TILT_ANGLE_LIMIT_FIELD: CustomConfigAngleField => turn_tilt_angle_limit -> AngleDegrees, offset: 145, scale: 100.0;
        TURN_TILT_START_ANGLE_FIELD: CustomConfigAngleField => turn_tilt_start_angle -> AngleDegrees, offset: 147, scale: 100.0;
        TURN_TILT_START_ERPM_FIELD: CustomConfigElectricalSpeedField => turn_tilt_start_erpm -> ElectricalSpeed, offset: 149;
        TURN_TILT_START_ERPM_BOOST_END_FIELD: CustomConfigElectricalSpeedField => turn_tilt_erpm_boost_end -> Rpm, offset: 153, map: ElectricalSpeed::rpm;
        TURN_TILT_YAW_AGGREGATE_FIELD: CustomConfigWireByteField => turn_tilt_yaw_aggregate -> AngleDegrees, offset: 155, map: |value: WireByte| value.scaled(1.0, 0.0, AngleDegrees::from_degrees);
        ATR_STRENGTH_UP_FIELD: CustomConfigPidScaleField => atr_strength_up -> PidScale, offset: 156, scale: 1000.0;
        ATR_STRENGTH_DOWN_FIELD: CustomConfigPidScaleField => atr_strength_down -> PidScale, offset: 158, scale: 1000.0;
        ATR_THRESHOLD_UP_FIELD: CustomConfigAngleField => atr_threshold_up -> AngleDegrees, offset: 160, scale: 100.0;
        ATR_THRESHOLD_DOWN_FIELD: CustomConfigAngleField => atr_threshold_down -> AngleDegrees, offset: 162, scale: 100.0;
        ATR_SPEED_BOOST_FIELD: CustomConfigPidScaleField => atr_speed_boost -> PidScale, offset: 164, scale: 10000.0;
        ATR_ANGLE_LIMIT_FIELD: CustomConfigAngleField => atr_angle_limit -> AngleDegrees, offset: 166, scale: 100.0;
        ATR_TRANSITION_BOOST_FIELD: CustomConfigPidScaleField => atr_transition_boost -> PidScale, offset: 168, scale: 1000.0;
        ATR_AMPS_ACCEL_RATIO_FIELD: CustomConfigPidScaleField => atr_amps_accel_ratio -> PidScale, offset: 172, scale: 100.0;
        ATR_AMPS_DECEL_RATIO_FIELD: CustomConfigPidScaleField => atr_amps_decel_ratio -> PidScale, offset: 174, scale: 100.0;
        BRAKE_TILT_STRENGTH_FIELD: CustomConfigPidScaleField => brake_tilt_strength -> PidScale, offset: 176, scale: 100.0;
        BRAKE_TILT_LINGERING_FIELD: CustomConfigPidScaleField => brake_tilt_lingering -> PidScale, offset: 178, scale: 1000.0;
    }
}

impl FloatOutBoyBalanceConfig<'_> {
    pub(crate) fn turn_tilt_erpm_boost(self) -> u16 {
        u16::from_be_bytes([self.0.as_bytes()[151], self.0.as_bytes()[152]])
    }

    pub(crate) fn torque_tilt_filter(self) -> FloatOutBoySetpointFilterConfig {
        FloatOutBoySetpointFilterConfig::new(
            self.torque_tilt_filter_time_constant(),
            self.torque_tilt_filter_on_speed_time_constant(),
            self.torque_tilt_filter_off_speed_time_constant(),
            self.torque_tilt_filter_on_speed_limit(),
            self.torque_tilt_filter_off_speed_limit(),
        )
    }

    pub(crate) fn atr_filter(self) -> FloatOutBoySetpointFilterConfig {
        FloatOutBoySetpointFilterConfig::new(
            self.atr_filter_time_constant(),
            self.atr_filter_on_speed_time_constant(),
            self.atr_filter_off_speed_time_constant(),
            self.atr_filter_on_speed_limit(),
            self.atr_filter_off_speed_limit(),
        )
    }
}

// The pinned cutoff serializes remote move fields immediately before startup
// tolerances.
vescpkg_rs::generated_custom_config_view! {
    #[derive(Debug, Clone, Copy, PartialEq)]
    pub(crate) struct FloatOutBoyRemoteConfig<'a>(&'a FloatOutBoyConfigImage);
    len: FLOAT_OUT_BOY_CONFIG_LEN;
    fields {
        MAX_MOVE_SPEED_FIELD: CustomConfigWireByteField => max_move_speed -> Speed, offset: 105, map: |value: WireByte| value.scaled(1.0, 0.0, Speed::from_kilometers_per_hour);
        GRACE_PERIOD_FIELD: CustomConfigSecondsField => grace_period -> VescSeconds, offset: 106, scale: 10.0;
    }
}

// Upstream HANDTEST temporarily disables tune modifiers at
// `third_party/float-out-boy/src/main.c:1431-1444`; these offsets follow the
// generated serialized field order in `third_party/float-out-boy/src/conf/settings.xml:3943-3961`.
const TILTBACK_CONSTANT_FIELD: CustomConfigResetField = vescpkg_rs::generated_custom_config_field!(CustomConfigResetField, len: FLOAT_OUT_BOY_CONFIG_LEN, offset: 87);
const TILTBACK_VARIABLE_FIELD: CustomConfigResetField = vescpkg_rs::generated_custom_config_field!(CustomConfigResetField, len: FLOAT_OUT_BOY_CONFIG_LEN, offset: 91);
const TORQUE_TILT_STRENGTH_FIELD: CustomConfigResetField = vescpkg_rs::generated_custom_config_field!(CustomConfigResetField, len: FLOAT_OUT_BOY_CONFIG_LEN, offset: 139);
const TORQUE_TILT_REGEN_STRENGTH_FIELD: CustomConfigResetField = vescpkg_rs::generated_custom_config_field!(CustomConfigResetField, len: FLOAT_OUT_BOY_CONFIG_LEN, offset: 141);
const TURN_TILT_STRENGTH_FIELD: CustomConfigResetField = vescpkg_rs::generated_custom_config_field!(CustomConfigResetField, len: FLOAT_OUT_BOY_CONFIG_LEN, offset: 143);
const ATR_STRENGTH_UP_FIELD: CustomConfigResetField = vescpkg_rs::generated_custom_config_field!(CustomConfigResetField, len: FLOAT_OUT_BOY_CONFIG_LEN, offset: 156);
const ATR_STRENGTH_DOWN_FIELD: CustomConfigResetField = vescpkg_rs::generated_custom_config_field!(CustomConfigResetField, len: FLOAT_OUT_BOY_CONFIG_LEN, offset: 158);
