//! Generate VESC firmware function-table descriptors from the pinned upstream header.

use std::{env, fmt::Write as _, fs, path::PathBuf};

#[path = "build/vesc_if.rs"]
mod vesc_if;

use vesc_if::{SlotDeclaration, SlotKind};

const HEADER_REPO: &str = "https://github.com/lukash/vesc_pkg_lib";
const HEADER_COMMIT: &str = "e8bdc8296b90a266713da3762868f0d18ec027fe";
const HEADER_PATH: &str = "third_party/vesc_pkg_lib/vesc_c_if.h";

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let workspace = manifest_dir.join("../..");
    let header = workspace.join(HEADER_PATH);
    let out = PathBuf::from(env::var("OUT_DIR").expect("out dir")).join("c_vesc_if.rs");

    println!("cargo::rustc-check-cfg=cfg(coverage)");
    println!("cargo:rerun-if-changed={}", header.display());
    let source = fs::read_to_string(&header).expect(HEADER_PATH);
    let slots = vesc_if::parse(&source)
        .unwrap_or_else(|error| panic!("failed to parse {}: {error}", header.display()));
    assert!(
        !slots.is_empty(),
        "failed to parse vesc_c_if slots from {}",
        header.display()
    );

    fs::write(out, generated_rust(&slots)).expect("write generated c_vesc_if.rs");
}

fn generated_rust(slots: &[SlotDeclaration]) -> String {
    let mut rust = String::new();

    rust.push_str("// Generated by crates/vescpkg-rs-sys/build.rs from ");
    rust.push_str(HEADER_PATH);
    rust.push_str(".\n");
    rust.push_str("// Do not edit by hand; update the vesc_pkg_lib submodule instead.\n\n");
    rust.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    rust.push_str("pub(crate) struct Slot {\n");
    rust.push_str("    pub(crate) name: &'static str,\n");
    rust.push_str("    pub(crate) index: usize,\n");
    rust.push_str("    pub(crate) vesc32_byte_offset: usize,\n");
    rust.push_str("    pub(crate) header_line: usize,\n");
    rust.push_str("    pub(crate) declaration: &'static str,\n");
    rust.push_str("    pub(crate) kind: crate::VescIfSlotKind,\n");
    rust.push_str("}\n\n");
    writeln!(
        rust,
        "pub(crate) const HEADER_REPO: &str = \"{HEADER_REPO}\";"
    )
    .expect("write generated Rust");
    writeln!(
        rust,
        "pub(crate) const HEADER_COMMIT: &str = \"{HEADER_COMMIT}\";"
    )
    .expect("write generated Rust");
    writeln!(
        rust,
        "pub(crate) const HEADER_PATH: &str = \"{HEADER_PATH}\";"
    )
    .expect("write generated Rust");
    writeln!(
        rust,
        "pub(crate) const FIELD_COUNT: usize = {};",
        slots.len()
    )
    .expect("write generated Rust");
    rust.push('\n');
    rust.push_str("pub(crate) const SLOTS: [Slot; FIELD_COUNT] = [\n");
    for slot in slots {
        writeln!(
            rust,
            "    Slot {{ name: \"{}\", index: {}, vesc32_byte_offset: {}, header_line: {}, declaration: {:?}, kind: crate::VescIfSlotKind::{} }},",
            slot.c_name,
            slot.index,
            slot.index * 4,
            slot.line,
            slot.declaration,
            slot_kind_name(slot.kind)
        )
        .expect("write generated Rust");
    }
    rust.push_str("];\n\n");

    rust.push_str("pub(crate) const ALL_ENTRIES: [crate::VescIfManifestEntry; FIELD_COUNT] = [\n");
    for slot in slots {
        writeln!(
            rust,
            "    crate::VescIfManifestEntry {{ slot: crate::VescIfSlot::new(\"{}\", {}), header_line: {}, declaration: {:?}, kind: crate::VescIfSlotKind::{} }},",
            slot.c_name,
            slot.index * 4,
            slot.line,
            slot.declaration,
            slot_kind_name(slot.kind)
        )
        .expect("write generated Rust");
    }
    rust.push_str("];\n\n");

    rust.push_str("pub(crate) const ALL_SLOTS: [crate::VescIfSlot; FIELD_COUNT] = [\n");
    for slot in slots {
        writeln!(
            rust,
            "    crate::VescIfSlot::new(\"{}\", {}),",
            slot.c_name,
            slot.index * 4
        )
        .expect("write generated Rust");
    }
    rust.push_str("];\n\n");

    rust.push_str("macro_rules! define_vesc_if_manifest_constants {\n");
    rust.push_str("    ($macro:ident) => {\n");
    rust.push_str("        $macro! {\n");
    for slot in slots {
        writeln!(
            rust,
            "            {} => {},",
            slot.rust_name.to_ascii_uppercase(),
            slot.rust_name
        )
        .expect("write generated Rust");
    }
    rust.push_str("        }\n");
    rust.push_str("    };\n");
    rust.push_str("}\n");
    rust.push_str("pub(crate) use define_vesc_if_manifest_constants;\n\n");

    rust.push_str("#[cfg(test)]\n");
    rust.push_str("macro_rules! rust_field_offsets {\n");
    rust.push_str("    ($table:path) => {\n");
    rust.push_str("        [\n");
    for slot in slots {
        writeln!(
            rust,
            "            core::mem::offset_of!($table, {}),",
            slot.rust_name
        )
        .expect("write generated Rust");
    }
    rust.push_str("        ]\n");
    rust.push_str("    };\n");
    rust.push_str("}\n");
    rust.push_str("#[cfg(test)]\n");
    rust.push_str("pub(crate) use rust_field_offsets;\n\n");

    for slot in slots {
        writeln!(rust, "pub(crate) mod {} {{", slot.rust_name).expect("write generated Rust");
        writeln!(
            rust,
            "    pub(crate) const NAME: &str = \"{}\";",
            slot.c_name
        )
        .expect("write generated Rust");
        writeln!(rust, "    pub(crate) const INDEX: usize = {};", slot.index)
            .expect("write generated Rust");
        rust.push_str("    pub(crate) const VESC32_BYTE_OFFSET: usize = INDEX * 4;\n");
        writeln!(
            rust,
            "    pub(crate) const HEADER_LINE: usize = {};",
            slot.line
        )
        .expect("write generated Rust");
        rust.push_str("}\n\n");
    }

    rust
}

fn slot_kind_name(kind: SlotKind) -> &'static str {
    match kind {
        SlotKind::Function => "Function",
        SlotKind::Scalar => "Scalar",
    }
}
