//! Generate VESC firmware function-table descriptors from the pinned upstream header.

use std::{env, fmt::Write as _, fs, path::PathBuf};

use quote::ToTokens;
use syn::{Fields, Item, Type};

const HEADER_REPO: &str = "https://github.com/lukash/vesc_pkg_lib";
const HEADER_COMMIT: &str = "e8bdc8296b90a266713da3762868f0d18ec027fe";
const HEADER_PATH: &str = "third_party/vesc_pkg_lib/vesc_c_if.h";
const VENDORED_HEADER_PATH: &str = "vendor/vesc_pkg_lib/vesc_c_if.h";

#[derive(Clone, Copy)]
enum SlotKind {
    Function,
    Scalar,
}

struct SlotDeclaration {
    c_name: String,
    index: usize,
    kind: SlotKind,
    signature: String,
    line: usize,
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let header = manifest_dir.join(VENDORED_HEADER_PATH);
    let workspace_header = manifest_dir.join("../..").join(HEADER_PATH);
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("out dir"));
    let out = out_dir.join("c_vesc_if.rs");
    let raw_slots = out_dir.join("raw_slots.rs");
    let bindings_path = out_dir.join("bindings.rs");

    println!("cargo::rustc-check-cfg=cfg(coverage)");
    println!("cargo:rerun-if-changed={}", header.display());
    if workspace_header.exists() {
        println!("cargo:rerun-if-changed={}", workspace_header.display());
        assert_eq!(
            fs::read(&header).expect("read vendored VESC header"),
            fs::read(&workspace_header).expect("read pinned VESC header"),
            "vendored VESC header must match the pinned vesc_pkg_lib submodule"
        );
    }

    let bindings = bindgen::Builder::default()
        .header(header.to_string_lossy())
        .allowlist_type("^(vesc_c_if|lbm_array_header_t)$")
        .clang_arg("-DIS_VESC_LIB")
        .clang_arg("--target=arm-none-eabi")
        .clang_arg("-mcpu=cortex-m4")
        .clang_arg("-mfpu=fpv4-sp-d16")
        .clang_arg("-mfloat-abi=hard")
        .use_core()
        .layout_tests(false)
        .generate_comments(false)
        .parse_callbacks(Box::new(bindgen::CargoCallbacks::new()))
        .generate()
        .expect("generate VESC C ABI bindings");
    let generated_bindings = bindings.to_string();
    fs::write(&bindings_path, &generated_bindings).expect("write VESC C ABI bindings");

    let mut slots = slots_from_bindings(&generated_bindings);
    let header_source = fs::read_to_string(&header).expect("read vendored VESC header");
    for slot in &mut slots {
        slot.line = header_source
            .lines()
            .position(|line| {
                line.split(|character: char| !character.is_ascii_alphanumeric() && character != '_')
                    .any(|word| word == slot.c_name)
            })
            .map_or(0, |line| line + 1);
    }
    assert!(
        !slots.is_empty(),
        "failed to parse vesc_c_if slots from {}",
        header.display()
    );

    fs::write(&out, generated_rust(&slots)).expect("write generated c_vesc_if.rs");
    fs::write(raw_slots, generated_raw_slots(&slots)).expect("write generated raw slots");
}

fn slots_from_bindings(bindings: &str) -> Vec<SlotDeclaration> {
    let file = syn::parse_file(bindings).expect("parse generated VESC Rust bindings");
    let table = file
        .items
        .into_iter()
        .find_map(|item| match item {
            Item::Struct(item) if item.ident == "vesc_c_if" => Some(item),
            _ => None,
        })
        .expect("bindgen must generate vesc_c_if");
    let Fields::Named(fields) = table.fields else {
        panic!("bindgen vesc_c_if must have named fields");
    };

    fields
        .named
        .into_iter()
        .enumerate()
        .map(|(index, field)| SlotDeclaration {
            c_name: field.ident.expect("named VESC_IF field").to_string(),
            index,
            kind: if is_function_slot(&field.ty) {
                SlotKind::Function
            } else {
                SlotKind::Scalar
            },
            signature: field.ty.to_token_stream().to_string(),
            line: 0,
        })
        .collect()
}

fn is_function_slot(ty: &Type) -> bool {
    let Type::Path(path) = ty else {
        return false;
    };
    let Some(ident) = path.path.segments.last().map(|segment| &segment.ident) else {
        return false;
    };
    ident != "u32" && ident != "lbm_uint"
}

#[allow(clippy::too_many_lines)]
fn generated_rust(slots: &[SlotDeclaration]) -> String {
    let mut rust = String::new();
    let callable_count = slots
        .iter()
        .filter(|slot| matches!(slot.kind, SlotKind::Function))
        .count();

    rust.push_str("// Generated by crates/vescpkg-rs-sys/build.rs from ");
    rust.push_str(HEADER_PATH);
    rust.push_str(".\n");
    rust.push_str("// Do not edit by hand; update the vesc_pkg_lib submodule instead.\n\n");
    writeln!(
        rust,
        "pub(crate) const HEADER_REPO: &str = \"{HEADER_REPO}\";"
    )
    .expect("write generated Rust");
    writeln!(
        rust,
        "pub(crate) const HEADER_COMMIT: &str = \"{HEADER_COMMIT}\";"
    )
    .expect("write generated Rust");
    writeln!(
        rust,
        "pub(crate) const HEADER_PATH: &str = \"{HEADER_PATH}\";"
    )
    .expect("write generated Rust");
    writeln!(
        rust,
        "pub(crate) const FIELD_COUNT: usize = {};",
        slots.len()
    )
    .expect("write generated Rust");
    writeln!(
        rust,
        "pub(crate) const CALLABLE_SLOT_COUNT: usize = {callable_count};"
    )
    .expect("write generated Rust");
    writeln!(
        rust,
        "pub(crate) const RAW_SHIM_COUNT: usize = {callable_count};"
    )
    .expect("write generated Rust");
    writeln!(
        rust,
        "pub(crate) const FIRMWARE_605_FIRST_SLOT: usize = {};",
        slot_index(slots, "lbm_start_flatten")
    )
    .expect("write generated Rust");
    writeln!(
        rust,
        "pub(crate) const FIRMWARE_606_FIRST_SLOT: usize = {};",
        slot_index(slots, "thread_set_priority")
    )
    .expect("write generated Rust");
    rust.push('\n');
    rust.push_str("pub(crate) const ALL_ENTRIES: [crate::VescIfManifestEntry; FIELD_COUNT] = [\n");
    for slot in slots {
        writeln!(
            rust,
            "    crate::VescIfManifestEntry {{ slot: crate::VescIfSlot::with_header_line(\"{}\", {}, {}), kind: crate::VescIfSlotKind::{}, signature: {:?} }},",
            slot.c_name,
            slot.index * 4,
            slot.line,
            slot_kind_name(slot.kind),
            slot.signature
        )
        .expect("write generated Rust");
    }
    rust.push_str("];\n\n");

    rust.push_str("pub(crate) const ALL_SLOTS: [crate::VescIfSlot; FIELD_COUNT] = [\n");
    for slot in slots {
        writeln!(
            rust,
            "    crate::VescIfSlot::with_header_line(\"{}\", {}, {}),",
            slot.c_name,
            slot.index * 4,
            slot.line
        )
        .expect("write generated Rust");
    }
    rust.push_str("];\n\n");

    rust.push_str("pub(crate) const RAW_SHIM_SLOTS: [crate::VescIfSlot; RAW_SHIM_COUNT] = [\n");
    for slot in slots {
        if matches!(slot.kind, SlotKind::Function) {
            writeln!(
                rust,
                "    crate::VescIfSlot::with_header_line(\"{}\", {}, {}),",
                slot.c_name,
                slot.index * 4,
                slot.line
            )
            .expect("write generated raw shim slot");
        }
    }
    rust.push_str("];\n\n");

    rust.push_str("pub(crate) const RAW_SHIM_SIGNATURES: [&str; RAW_SHIM_COUNT] = [\n");
    for slot in slots {
        if matches!(slot.kind, SlotKind::Function) {
            writeln!(rust, "    {:?},", slot.signature)
                .expect("write generated raw shim signature");
        }
    }
    rust.push_str("];\n\n");

    rust.push_str("pub(crate) const SLOTS: [crate::VescIfSlot; FIELD_COUNT] = ALL_SLOTS;\n\n");

    rust.push_str("#[allow(clippy::too_many_lines)]\n");
    rust.push_str(
        "pub(crate) fn presence(table: &crate::bindgen::vesc_c_if) -> crate::VescIfPresence {\n",
    );
    rust.push_str("    let mut presence = crate::VescIfPresence::empty();\n");
    for slot in slots {
        match slot.kind {
            SlotKind::Function => writeln!(
                rust,
                "    if table.{}.is_some() {{ presence.set({}); }}",
                slot.c_name, slot.index
            ),
            SlotKind::Scalar => writeln!(rust, "    presence.set({});", slot.index),
        }
        .expect("write generated Rust");
    }
    rust.push_str("    presence\n}\n\n");

    rust.push_str("macro_rules! define_vesc_if_manifest_constants {\n");
    rust.push_str("    ($macro:ident) => {\n");
    rust.push_str("        $macro! {\n");
    for slot in slots {
        writeln!(
            rust,
            "            {} => \"{}\", {}, {},",
            slot.c_name.to_ascii_uppercase(),
            slot.c_name,
            slot.index * 4,
            slot.line
        )
        .expect("write generated Rust");
    }
    rust.push_str("        }\n");
    rust.push_str("    };\n");
    rust.push_str("}\n");
    rust.push_str("pub(crate) use define_vesc_if_manifest_constants;\n\n");

    rust.push_str("macro_rules! define_vesc_if_callable_names {\n");
    rust.push_str("    ($macro:ident) => {\n");
    rust.push_str("        $macro! {\n");
    for slot in slots {
        if matches!(slot.kind, SlotKind::Function) {
            writeln!(rust, "            {},", slot.c_name).expect("write generated Rust");
        }
    }
    rust.push_str("        }\n");
    rust.push_str("    };\n");
    rust.push_str("}\n");
    rust.push_str("pub(crate) use define_vesc_if_callable_names;\n\n");

    for slot in slots {
        writeln!(rust, "pub(crate) mod {} {{", slot.c_name).expect("write generated Rust");
        writeln!(
            rust,
            "    pub(crate) const NAME: &str = \"{}\";",
            slot.c_name
        )
        .expect("write generated Rust");
        writeln!(rust, "    pub(crate) const INDEX: usize = {};", slot.index)
            .expect("write generated Rust");
        rust.push_str("    pub(crate) const VESC32_BYTE_OFFSET: usize = INDEX * 4;\n");
        writeln!(
            rust,
            "    pub(crate) const HEADER_LINE: usize = {};",
            slot.line
        )
        .expect("write generated Rust");
        rust.push_str("}\n\n");
    }

    rust
}

fn generated_raw_slots(slots: &[SlotDeclaration]) -> String {
    let mut rust = String::new();
    rust.push_str("// Generated raw resolvers for every callable VESC_IF slot.\n");
    rust.push_str("// Do not edit by hand; update the pinned VESC header instead.\n\n");
    for slot in slots {
        if !matches!(slot.kind, SlotKind::Function) {
            continue;
        }
        writeln!(
            rust,
            "/// Resolve the raw `{}` function slot without invoking it.",
            slot.c_name
        )
        .expect("write generated raw resolver docs");
        rust.push_str("///\n/// # Safety\n/// The returned pointer must be called only with the exact ABI contract in the manifest.\n");
        writeln!(
            rust,
            "#[inline(always)]\npub unsafe fn resolve_{}() -> {} {{",
            slot.c_name, slot.signature
        )
        .expect("write generated raw resolver");
        rust.push_str("    #[cfg(all(target_arch = \"arm\", not(test)))]\n");
        rust.push_str("    {\n");
        writeln!(
            rust,
            "        let address = unsafe {{ super::load_vesc_if_word_from::<{}>(crate::VescIfAbi::BASE_ADDR.0) }};",
            slot.index * 4
        )
        .expect("write generated ARM resolver");
        writeln!(
            rust,
            "        unsafe {{ core::mem::transmute::<usize, {}>(address) }}",
            slot.signature
        )
        .expect("write generated ARM resolver");
        rust.push_str("    }\n");
        rust.push_str("    #[cfg(not(all(target_arch = \"arm\", not(test))))]\n");
        rust.push_str("    {\n");
        writeln!(
            rust,
            "        unsafe {{ (*super::vesc_if()).{} }}",
            slot.c_name
        )
        .expect("write generated host resolver");
        rust.push_str("    }\n");
        rust.push_str("}\n\n");
    }
    rust
}

fn slot_index(slots: &[SlotDeclaration], name: &str) -> usize {
    slots
        .iter()
        .find(|slot| slot.c_name == name)
        .unwrap_or_else(|| panic!("bindgen VESC_IF must contain {name}"))
        .index
}

fn slot_kind_name(kind: SlotKind) -> &'static str {
    match kind {
        SlotKind::Function => "Function",
        SlotKind::Scalar => "Scalar",
    }
}
