//! LispBM extension descriptor validation and registration errors.

use core::ffi::CStr;

use vescpkg_rs_sys::{ExtensionHandler, LbmValue};

const LBM_INT_TAG: u32 = 0x8;
const LBM_VALUE_SHIFT: u32 = 4;
const LBM_INT_MIN: i32 = -(1 << 27);
const LBM_INT_MAX: i32 = (1 << 27) - 1;

const fn encode_integer(value: i32) -> u32 {
    value.wrapping_shl(LBM_VALUE_SHIFT) as u32 | LBM_INT_TAG
}

#[cfg(any(test, not(target_arch = "arm")))]
const fn decode_integer(value: u32) -> i32 {
    (value as i32) >> LBM_VALUE_SHIFT
}

/// A LispBM value that can only be produced by the SDK's typed argument API.
#[derive(Clone, Copy, PartialEq, Eq)]
pub struct LispValue(LbmValue);

impl LispValue {
    /// Create a LispBM integer value using the device's integer encoding.
    pub const fn integer(value: i32) -> Option<Self> {
        if value >= LBM_INT_MIN && value <= LBM_INT_MAX {
            Some(Self(LbmValue(encode_integer(value))))
        } else {
            None
        }
    }

    pub(crate) const fn raw(self) -> LbmValue {
        self.0
    }

    #[cfg(not(test))]
    pub(crate) const fn from_raw(value: LbmValue) -> Self {
        Self(value)
    }
}

/// Extension-name validation failures.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ExtensionNameError {
    /// The name did not start with the required `ext-` prefix.
    MissingExtPrefix,
}

/// Errors returned when extension registration fails.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RegisterError {
    /// The extension name failed validation.
    InvalidExtensionName,
    /// Firmware rejected the registration request.
    FirmwareRejected,
    /// The package loader metadata was unavailable.
    LoaderUnavailable,
}

/// A static name assigned to a LispBM extension.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(transparent)]
pub struct ExtensionName(&'static [u8]);

impl ExtensionName {
    /// Build a name from the terminated storage generated by `extension_name!`.
    #[doc(hidden)]
    #[must_use]
    pub const fn __from_terminated(name: &'static str) -> Option<Self> {
        match CStr::from_bytes_with_nul(name.as_bytes()) {
            Ok(_) => Some(Self(name.as_bytes())),
            Err(_) => None,
        }
    }

    pub(crate) const fn as_cstr(self) -> &'static CStr {
        // SAFETY: the macro support hook validates the terminating NUL byte.
        unsafe { CStr::from_bytes_with_nul_unchecked(self.0) }
    }

    /// Return the validated Rust extension name without its ABI terminator.
    pub fn as_str(self) -> &'static str {
        let bytes = &self.0[..self.0.len() - 1];
        // SAFETY: the macro support hook accepts only valid C strings built
        // from UTF-8 Rust string literals.
        unsafe { core::str::from_utf8_unchecked(bytes) }
    }
}

/// Create a checked static LispBM extension name from a Rust string literal.
#[macro_export]
macro_rules! extension_name {
    ($name:literal) => {
        const {
            match $crate::ExtensionName::__from_terminated(concat!($name, "\0")) {
                Some(name) => name,
                None => panic!("extension name literal must not contain NUL"),
            }
        }
    };
}

/// A validated extension registration request.
#[derive(Clone, Copy)]
pub struct ExtensionDescriptor {
    name: ExtensionName,
    #[cfg_attr(
        not(any(test, feature = "test-support", target_arch = "arm")),
        allow(dead_code)
    )]
    handler: ExtensionHandler,
}

impl ExtensionDescriptor {
    pub(crate) const fn from_handler(name: ExtensionName, handler: ExtensionHandler) -> Self {
        Self { name, handler }
    }

    /// Build a descriptor from its name and handler.
    /// Build a descriptor for a stateless typed extension callback.
    #[inline(always)]
    pub const fn typed<T: LbmExtension>(name: ExtensionName) -> Self {
        Self::from_handler(name, lbm_extension_handler::<T>)
    }

    /// Build a descriptor for a runtime-state-backed typed extension callback.
    #[inline(always)]
    pub const fn stateful<T: StatefulLbmExtension>(name: ExtensionName) -> Self {
        Self::from_handler(name, stateful_lbm_extension_handler::<T>)
    }

    /// Return the descriptor name.
    pub const fn name(self) -> ExtensionName {
        self.name
    }

    #[cfg(any(test, feature = "test-support", target_arch = "arm"))]
    /// Return the descriptor handler.
    pub(crate) const fn handler(self) -> ExtensionHandler {
        self.handler
    }

    /// Validate the descriptor name prefix expected by the firmware.
    pub fn validate(self) -> Result<Self, ExtensionNameError> {
        if self.name.as_cstr().to_bytes().starts_with(b"ext-") {
            Ok(self)
        } else {
            Err(ExtensionNameError::MissingExtPrefix)
        }
    }
}

/// Typed LispBM extension callback arguments.
pub struct LispArgs<'a> {
    values: &'a [LbmValue],
}

impl LispArgs<'static> {
    /// Construct an empty extension argument list.
    #[must_use]
    pub const fn empty() -> Self {
        Self { values: &[] }
    }
}

impl LispArgs<'_> {
    fn from_raw(args: *mut u32, arg_count: u32) -> Option<Self> {
        let len = usize::try_from(arg_count).ok()?;
        if len == 0 {
            return Some(Self { values: &[] });
        }
        unsafe { crate::firmware::lbm_args(args, arg_count).map(|values| Self { values }) }
    }

    /// Return the number of arguments supplied by LispBM.
    pub const fn len(&self) -> usize {
        self.values.len()
    }

    /// Return whether LispBM supplied no arguments.
    pub const fn is_empty(&self) -> bool {
        self.values.is_empty()
    }

    /// Return an argument as an integer when it exists.
    pub fn integer(&self, index: usize) -> Option<i32> {
        let value = *self.values.get(index)?;
        #[cfg(all(not(test), target_arch = "arm"))]
        {
            let firmware = crate::Firmware::new();
            Some(firmware.lisp().decode_i32(LispValue::from_raw(value)))
        }
        #[cfg(any(test, not(target_arch = "arm")))]
        {
            Some(decode_integer(value.0))
        }
    }

    /// Return the firmware true value.
    pub fn true_value(&self) -> LispValue {
        #[cfg(all(not(test), target_arch = "arm"))]
        {
            let firmware = crate::Firmware::new();
            firmware.lisp().encode_true()
        }
        #[cfg(any(test, not(target_arch = "arm")))]
        {
            LispValue(LbmValue(1))
        }
    }

    /// Return the firmware nil value.
    pub fn nil_value(&self) -> LispValue {
        #[cfg(all(not(test), target_arch = "arm"))]
        {
            let firmware = crate::Firmware::new();
            firmware.lisp().encode_nil()
        }
        #[cfg(any(test, not(target_arch = "arm")))]
        {
            LispValue(LbmValue(0))
        }
    }
}

/// Rust implementation for a LispBM extension callback.
pub trait LbmExtension {
    /// Handle one extension call.
    fn call(args: LispArgs<'_>) -> LispValue;
}

/// State-backed LispBM extension behavior for package authors.
pub trait StatefulLbmExtension {
    /// Package state installed by startup.
    type State: 'static;

    /// Runtime state shared with package callbacks.
    fn runtime_state() -> &'static crate::PackageStateStore<Self::State>;

    /// Handle one extension call with the current package state.
    fn call(state: &mut Self::State, args: LispArgs<'_>) -> LispValue;
}

/// Firmware ABI trampoline for a typed LispBM extension callback.
///
/// # Safety
///
/// `args` must be null with `arg_count == 0` or point to `arg_count` LispBM values that stay valid for
/// this call.
pub unsafe extern "C" fn lbm_extension_handler<T: LbmExtension>(
    args: *mut u32,
    arg_count: u32,
) -> u32 {
    let Some(args) = LispArgs::from_raw(args, arg_count) else {
        return 0;
    };
    T::call(args).raw().0
}

/// Firmware ABI trampoline for a state-backed LispBM extension callback.
///
/// # Safety
///
/// `args` must be null with `arg_count == 0` or point to `arg_count` LispBM values that stay valid for
/// this call.
pub unsafe extern "C" fn stateful_lbm_extension_handler<T: StatefulLbmExtension>(
    args: *mut u32,
    arg_count: u32,
) -> u32 {
    let Some(args) = LispArgs::from_raw(args, arg_count) else {
        return 0;
    };
    let nil = args.nil_value();
    T::runtime_state()
        .with_mut(|state| T::call(state, args))
        .unwrap_or(nil)
        .raw()
        .0
}

#[cfg(test)]
mod tests {
    use super::{LispArgs, LispValue, StatefulLbmExtension, stateful_lbm_extension_handler};
    use crate::PackageStateStore;
    use std::boxed::Box;

    #[derive(Debug, PartialEq, Eq)]
    struct State {
        calls: u32,
    }

    struct TestExtension;

    struct IntegerExtension;

    struct EchoIntegerExtension;

    static SLOT: PackageStateStore<State> = PackageStateStore::new();

    impl StatefulLbmExtension for TestExtension {
        type State = State;

        fn runtime_state() -> &'static PackageStateStore<Self::State> {
            &SLOT
        }

        fn call(state: &mut Self::State, args: LispArgs<'_>) -> LispValue {
            state.calls += 1;
            args.true_value()
        }
    }

    impl super::LbmExtension for IntegerExtension {
        fn call(_args: LispArgs<'_>) -> LispValue {
            LispValue::integer(42).unwrap()
        }
    }

    impl super::LbmExtension for EchoIntegerExtension {
        fn call(args: LispArgs<'_>) -> LispValue {
            LispValue::integer(args.integer(0).unwrap_or_default()).unwrap()
        }
    }

    #[test]
    fn stateful_lbm_extension_handler_passes_package_state() {
        assert_eq!(
            unsafe { stateful_lbm_extension_handler::<TestExtension>(core::ptr::null_mut(), 0) },
            0
        );

        let state = Box::leak(Box::new(State { calls: 0 }));
        unsafe { SLOT.install(state) };

        assert_eq!(
            unsafe { stateful_lbm_extension_handler::<TestExtension>(core::ptr::null_mut(), 0) },
            1
        );
        assert_eq!(*state, State { calls: 1 });

        SLOT.clear();
    }

    #[test]
    fn typed_lisp_integer_keeps_device_encoding_inside_the_sdk() {
        assert_eq!(
            unsafe { super::lbm_extension_handler::<IntegerExtension>(core::ptr::null_mut(), 0) },
            super::encode_integer(42),
        );
    }

    #[test]
    fn typed_lisp_integer_rejects_values_outside_the_immediate_payload() {
        assert!(LispValue::integer(super::LBM_INT_MIN).is_some());
        assert!(LispValue::integer(super::LBM_INT_MAX).is_some());
        assert!(LispValue::integer(super::LBM_INT_MIN - 1).is_none());
        assert!(LispValue::integer(super::LBM_INT_MAX + 1).is_none());
    }

    #[test]
    fn typed_lisp_args_decode_device_integer_encoding() {
        let mut args = [super::encode_integer(37)];
        assert_eq!(
            unsafe {
                super::lbm_extension_handler::<EchoIntegerExtension>(
                    args.as_mut_ptr().cast(),
                    args.len() as u32,
                )
            },
            super::encode_integer(37),
        );
    }

    #[test]
    fn extension_name_exposes_rust_text_without_abi_terminator() {
        let name = crate::extension_name!("ext-example");

        assert_eq!(name.as_str(), "ext-example");
        assert_eq!(
            super::ExtensionName::__from_terminated("ext-example\0")
                .map(super::ExtensionName::as_str),
            Some("ext-example")
        );
        assert!(super::ExtensionName::__from_terminated("ext-example").is_none());
        assert!(super::ExtensionName::__from_terminated("ext\0-example\0").is_none());
    }
}
