//! Safe adapters for firmware callback pointers.

use core::ffi::{c_int, c_void};
use core::ptr::{self, NonNull};

use vescpkg_rs_sys::{
    AppDataPacket, ConfigPayload, ConfigXmlBytes, LbmValue, LibInfo, MutablePacket, StopHandler,
};

/// Borrow nullable loader metadata from a firmware entrypoint.
pub fn loader_info_mut(info: *mut LibInfo) -> Option<&'static mut LibInfo> {
    NonNull::new(info).map(|mut info| unsafe { info.as_mut() })
}

/// Clear package state and stop metadata when startup fails.
pub fn clear_loader_info(info: *mut LibInfo) {
    if let Some(info) = loader_info_mut(info) {
        info.arg = ptr::null_mut();
        info.stop_fun = None;
    }
}

/// Store package state and a stop hook in loader metadata.
pub fn install_loader_state<T>(
    info: *mut LibInfo,
    stop_handler: StopHandler,
    state: &mut T,
) -> bool {
    if let Some(info) = loader_info_mut(info) {
        info.arg = ptr::from_mut(state).cast();
        info.stop_fun = Some(stop_handler);
    }
    true
}

/// Recover typed package state from loader metadata.
pub fn loader_state_mut<T: 'static>(info: &mut LibInfo) -> Option<&mut T> {
    arg_mut(info.arg)
}

/// Recover typed package state from a firmware ARG pointer.
pub fn arg_mut<T: 'static>(arg: *mut c_void) -> Option<&'static mut T> {
    NonNull::new(arg.cast::<T>()).map(|mut arg| unsafe { arg.as_mut() })
}

/// Borrow typed package state from a firmware ARG pointer.
pub fn arg_ref<T: 'static>(arg: *mut c_void) -> Option<&'static T> {
    NonNull::new(arg.cast::<T>()).map(|arg| unsafe { arg.as_ref() })
}

/// Typed context passed to package stop callbacks.
pub struct StopContext<T: 'static> {
    arg: *mut c_void,
    state: Option<&'static T>,
}

impl<T: 'static> StopContext<T> {
    /// Borrow the package state, when firmware provided one.
    pub const fn state(&self) -> Option<&T> {
        self.state
    }

    /// Reclaim the package state allocation so dropping it frees via firmware.
    pub fn reclaim_allocation<'a, B: crate::AllocBindings>(
        self,
        len: usize,
        bindings: &'a B,
    ) -> Option<crate::FirmwareAllocation<'a, T, B>> {
        crate::reclaim_firmware_allocation(self.arg.cast::<T>(), len, bindings)
    }
}

/// Rust implementation for a package stop callback.
pub trait StopCallback {
    /// Package state stored in loader metadata.
    type State: 'static;

    /// Stop package-owned runtime resources.
    fn stop(context: StopContext<Self::State>);
}

/// Firmware ABI trampoline for a typed package stop callback.
///
/// # Safety
///
/// `arg` must be null or point to a valid `T::State` value for the duration of this call.
pub unsafe extern "C" fn stop_callback<T: StopCallback>(arg: *mut c_void) {
    T::stop(StopContext {
        arg,
        state: arg_ref::<T::State>(arg),
    });
}

/// Convert firmware app-data callback arguments into a packet view.
pub fn app_data_packet(data: *mut u8, len: u32) -> Option<AppDataPacket<'static>> {
    let len = usize::try_from(len).ok()?;
    borrowed_bytes(data.cast_const(), len).map(AppDataPacket)
}

/// Rust implementation for an app-data callback.
pub trait AppDataCallback {
    /// Handle one firmware app-data packet.
    fn handle(packet: AppDataPacket<'static>);
}

/// Firmware ABI trampoline for a typed app-data callback.
///
/// # Safety
///
/// `data` must be null with `len == 0` or point to `len` readable bytes that stay valid for this
/// call.
pub unsafe extern "C" fn app_data_callback<T: AppDataCallback>(data: *mut u8, len: u32) {
    if let Some(packet) = app_data_packet(data, len) {
        T::handle(packet);
    }
}

/// Define a package-local app-data callback symbol backed by a typed Rust handler.
#[macro_export]
macro_rules! firmware_app_data_callback {
    ($name:ident, $callback:ty) => {
        #[doc = "Package-local firmware app-data callback generated by `firmware_app_data_callback!`."]
        #[cfg(all(not(test), target_arch = "arm"))]
        #[unsafe(no_mangle)]
        #[inline(never)]
        pub unsafe extern "C" fn $name(data: *mut u8, len: u32) {
            unsafe { $crate::app_data_callback::<$callback>(data, len) };
        }
    };
}

/// Convert LispBM extension callback arguments into typed values.
pub fn lbm_args(args: *mut u32, argn: u32) -> Option<&'static [LbmValue]> {
    let len = usize::try_from(argn).ok()?;
    let args = NonNull::new(args.cast::<LbmValue>())?;
    Some(unsafe { core::slice::from_raw_parts(args.as_ptr().cast_const(), len) })
}

/// Mutable custom-config output buffer for `get_cfg` callbacks.
pub struct CustomConfigGetBuffer(MutablePacket<'static>);

impl CustomConfigGetBuffer {
    /// Borrow the firmware-provided output buffer.
    pub fn new(buffer: *mut u8, len: usize) -> Option<Self> {
        mutable_bytes(buffer, len).map(Self)
    }

    /// Write serialized config bytes into the firmware-provided output buffer.
    pub fn write(&mut self, payload: ConfigPayload<'_>) -> c_int {
        if payload.0.len() > self.0.0.len() {
            return 0;
        }
        self.0.0[..payload.0.len()].copy_from_slice(payload.0);
        payload.0.len() as c_int
    }
}

/// Borrowed custom-config input for `set_cfg` callbacks.
pub fn custom_config_payload(buffer: *mut u8, len: usize) -> Option<ConfigPayload<'static>> {
    borrowed_bytes(buffer.cast_const(), len).map(ConfigPayload)
}

/// Rust implementation for VESC Tool custom-config callbacks.
pub trait CustomConfigCallback {
    /// Serialized config byte length.
    const CONFIG_LEN: usize;

    /// Return config bytes for a get callback.
    fn get_config(is_default: bool) -> Option<ConfigPayload<'static>>;

    /// Store config bytes from a set callback.
    fn set_config(config: ConfigPayload<'static>) -> bool;

    /// Return the config XML bytes.
    fn config_xml() -> ConfigXmlBytes<'static>;
}

/// Firmware ABI trampoline for custom-config get callbacks.
///
/// # Safety
///
/// `buffer` must point to `T::CONFIG_LEN` writable bytes when the firmware expects a config copy.
pub unsafe extern "C" fn custom_config_get<T: CustomConfigCallback>(
    buffer: *mut u8,
    is_default: bool,
) -> c_int {
    let Some(config) = T::get_config(is_default) else {
        return 0;
    };
    let Some(mut buffer) = CustomConfigGetBuffer::new(buffer, T::CONFIG_LEN) else {
        return 0;
    };
    buffer.write(config)
}

/// Firmware ABI trampoline for custom-config set callbacks.
///
/// # Safety
///
/// `buffer` must point to `T::CONFIG_LEN` readable bytes for the duration of this call.
pub unsafe extern "C" fn custom_config_set<T: CustomConfigCallback>(buffer: *mut u8) -> bool {
    let Some(config) = custom_config_payload(buffer, T::CONFIG_LEN) else {
        return false;
    };
    T::set_config(config)
}

/// Firmware XML pointer output for `get_cfg_xml` callbacks.
pub struct CustomConfigXmlOut(NonNull<*mut u8>);

impl CustomConfigXmlOut {
    /// Borrow the firmware-provided XML output pointer slot.
    pub fn new(buffer: *mut *mut u8) -> Option<Self> {
        NonNull::new(buffer).map(Self)
    }

    /// Return XML bytes to firmware by pointer and byte count.
    pub fn return_xml(self, xml: ConfigXmlBytes<'static>) -> c_int {
        unsafe { *self.0.as_ptr() = xml.0.as_ptr().cast_mut() };
        xml.0.len() as c_int
    }
}

/// Firmware ABI trampoline for custom-config XML callbacks.
///
/// # Safety
///
/// `buffer` must be a valid writable pointer to the firmware's output pointer slot.
pub unsafe extern "C" fn custom_config_xml<T: CustomConfigCallback>(buffer: *mut *mut u8) -> c_int {
    let Some(buffer) = CustomConfigXmlOut::new(buffer) else {
        return 0;
    };
    buffer.return_xml(T::config_xml())
}

/// Define package-local custom-config callback symbols backed by a typed Rust handler.
#[macro_export]
macro_rules! firmware_custom_config_callbacks {
    ($get_name:ident, $set_name:ident, $xml_name:ident, $callback:ty) => {
        #[doc = "Package-local firmware custom-config get callback generated by `firmware_custom_config_callbacks!`."]
        #[cfg(all(not(test), target_arch = "arm"))]
        #[unsafe(no_mangle)]
        #[inline(never)]
        pub unsafe extern "C" fn $get_name(
            buffer: *mut u8,
            is_default: bool,
        ) -> core::ffi::c_int {
            unsafe { $crate::custom_config_get::<$callback>(buffer, is_default) }
        }

        #[doc = "Package-local firmware custom-config set callback generated by `firmware_custom_config_callbacks!`."]
        #[cfg(all(not(test), target_arch = "arm"))]
        #[unsafe(no_mangle)]
        #[inline(never)]
        pub unsafe extern "C" fn $set_name(buffer: *mut u8) -> bool {
            unsafe { $crate::custom_config_set::<$callback>(buffer) }
        }

        #[doc = "Package-local firmware custom-config XML callback generated by `firmware_custom_config_callbacks!`."]
        #[cfg(all(not(test), target_arch = "arm"))]
        #[unsafe(no_mangle)]
        #[inline(never)]
        pub unsafe extern "C" fn $xml_name(buffer: *mut *mut u8) -> core::ffi::c_int {
            unsafe { $crate::custom_config_xml::<$callback>(buffer) }
        }
    };
}

/// Borrow XML bytes from a rebased firmware image address.
pub fn config_xml_bytes(data: *const u8, len: usize) -> Option<ConfigXmlBytes<'static>> {
    borrowed_bytes(data, len).map(ConfigXmlBytes)
}

/// Copy a fixed-size firmware array into Rust-owned storage.
pub fn firmware_array<T: Copy, const N: usize>(values: *const T) -> Option<[T; N]> {
    let values = NonNull::new(values.cast_mut())?;
    let values = unsafe { core::slice::from_raw_parts(values.as_ptr().cast_const(), N) };
    values.try_into().ok()
}

/// Compute the loaded-image offset for a function symbol in a relocated firmware package.
#[macro_export]
macro_rules! firmware_loaded_function_offset {
    ($symbol:path) => {{
        let loaded_symbol: usize;
        unsafe {
            core::arch::asm!(
                "adr {loaded_symbol}, {symbol}",
                loaded_symbol = out(reg) loaded_symbol,
                symbol = sym $symbol,
                options(nomem, nostack, preserves_flags),
            );
        }
        let loaded_symbol = loaded_symbol & !1;
        let image_symbol = $symbol as *const () as usize & !1;
        (loaded_symbol - image_symbol) as u32
    }};
}

/// Return a Thumb handler pointer for a function symbol in a relocated firmware package.
#[macro_export]
macro_rules! firmware_rebased_thumb_handler {
    ($handler:path, $handler_ty:ty) => {{
        let address: usize;
        unsafe {
            core::arch::asm!(
                "adr.w {address}, {handler}",
                address = out(reg) address,
                handler = sym $handler,
                options(nomem, nostack, preserves_flags),
            );
            core::mem::transmute::<usize, $handler_ty>(address | 1)
        }
    }};
}

fn borrowed_bytes(data: *const u8, len: usize) -> Option<&'static [u8]> {
    let data = NonNull::new(data.cast_mut())?;
    Some(unsafe { core::slice::from_raw_parts(data.as_ptr().cast_const(), len) })
}

fn mutable_bytes(data: *mut u8, len: usize) -> Option<MutablePacket<'static>> {
    let data = NonNull::new(data)?;
    Some(MutablePacket(unsafe {
        core::slice::from_raw_parts_mut(data.as_ptr(), len)
    }))
}

#[cfg(test)]
mod tests {
    use super::*;

    unsafe extern "C" fn stop(_arg: *mut c_void) {}

    #[test]
    fn loader_state_round_trips_through_loader_info() {
        let mut state = 42_u32;
        let mut info = LibInfo {
            stop_fun: None,
            arg: ptr::null_mut(),
            base_addr: 0,
        };

        assert!(install_loader_state(&mut info, stop, &mut state));
        *loader_state_mut::<u32>(&mut info).expect("state") = 7;

        assert_eq!(state, 7);
        assert!(info.stop_fun.is_some());

        clear_loader_info(&mut info);
        assert!(info.arg.is_null());
        assert!(info.stop_fun.is_none());
    }

    #[test]
    fn custom_config_get_buffer_writes_payload_bytes() {
        let mut buffer = [0_u8; 3];
        let mut output =
            CustomConfigGetBuffer::new(buffer.as_mut_ptr(), buffer.len()).expect("config output");

        assert_eq!(output.write(ConfigPayload(b"abc")), 3);
        assert_eq!(&buffer, b"abc");
        assert!(CustomConfigGetBuffer::new(ptr::null_mut(), 3).is_none());
    }

    #[test]
    fn firmware_packet_and_array_helpers_reject_null() {
        assert!(app_data_packet(ptr::null_mut(), 3).is_none());
        assert!(firmware_array::<f32, 3>(ptr::null()).is_none());

        let values = [1.0_f32, 2.0, 3.0];
        assert_eq!(firmware_array::<f32, 3>(values.as_ptr()), Some(values));
    }

    #[test]
    fn custom_config_xml_out_writes_pointer_and_len() {
        let xml = b"<xml/>";
        let mut out = ptr::null_mut();
        let output = CustomConfigXmlOut::new(&mut out).expect("xml output");

        assert_eq!(output.return_xml(ConfigXmlBytes(xml)), 6);
        assert_eq!(out, xml.as_ptr().cast_mut());
        assert!(CustomConfigXmlOut::new(ptr::null_mut()).is_none());
    }
}
